### ISSUE TITLE
Debugging Support in VS Code IDE

### ISSUE THREAD

**Issue by dtarnawsky** [ionic-team/vscode-extension#10]
The option to Run on Web, iOS and Android should allow debugging in the VSCode IDE (capturing console, allowing inspection, network, etc). At the moment you would need to attach to the device using Safari or Chrome Inspect.

**Comment by ChrsCrss** [comment]
Adding configurable browser launch options would be great, like `--remote-debugging-port=9222 --user-data-dir=temp --disable-web-security` for chrome. This should be sufficient at least for debugging on web.

**Comment by dtarnawsky** [comment]
Version 1.4.1 now has a "debug" button for the Run on Web option which will launch a debugging session into either Chrome (default) or (MS Edge). For now I'll close out this issue. Roadmap has a plan for debugging for iOS and Android but these are much bigger topics.

@neonish, take a look at 1.4.1 and see if the debug for web option meets your needs.

**Comment by aaronksaunders** [comment]
Pointer on how to reconfigure to not use   chrome by default? Or should I open another issue?

**Comment by philkonick** [comment]
@dtarnawsky Works great for me.

Is there a way to launch debugging in chrome in an existing window like Run in Web? Instead of launching in a new window without the default user context.

**Comment by dtarnawsky** [comment]
Hey @aaronksaunders, If you click Settings you can change the default browser for debugging from Chrome to Edge.

**Comment by dtarnawsky** [comment]
Hey @philkonick, the browser (Chrome or Edge) needs to be launched with the parameters: `--remote-debugging-port=9222 --user-data-dir=remote-profile` for it to be debuggable in VS Code. This will launch a separate browser instance if the current one doesn't support remote debugging. The Chromium team describe this [here](https://blog.chromium.org/2011/05/remote-debugging-with-chrome-developer.html)
