### ISSUE TITLE
Extension wont work in shared repository any more - Ionic + Firebase Functions

### ISSUE THREAD

**Issue by crebuh** [ionic-team/vscode-extension#100]
Hello Guys,

this is probably more a configuration issue, than a bug or anything else. Although the issue was not there in the past. Here is the problem.

I have multiple Ionic/Angular/Capacitor projects. One of them includes a subfolder called "functions" which holds a firebase project with a couple of functions. In the past the Extension ignored that folder and correctly initialised the extension. 

But in the last days I found out that the Ionic extension is using the functions folder default project.
![Screenshot 2023-04-03 at 16 58 44](https://user-images.githubusercontent.com/5765733/229548969-96ca963d-7cbd-423b-9354-484970558516.jpg)

But when I move the functions folder in a "firebase" folder for example it works again.

![Screenshot 2023-04-03 at 16 59 10](https://user-images.githubusercontent.com/5765733/229548978-9894c35c-207e-41c3-bd37-1964286c4f56.jpg)

Any idea how to configure that behaviour without adding the additional folder for firebase?

**Comment by dtarnawsky** [comment]
Taking a look at this now. The extension has to make a determination as to whether your project is a set of folders that are a mono-repo and it looks like that is what is happening. 

In v1.34 it will inspect a little deeper and see if the package dependencies look like things that you might be interested in building like `@capacitor/core`, `@angular/core`, `@ionic/vue`, etc. In which case this firebase folder won't look interesting enough to make it appear like a mono repo. v1.34 should be out today or tomorrow.

**Comment by crebuh** [comment]
Awesome, I think checking the package.json should be a good indication whether the project is really an Ionic Project or not. Looking forward to the new version :)

**Comment by dtarnawsky** [comment]
This should now be fixed in v1.34 which was just released.

**Comment by crebuh** [comment]
Awesome just tested it and it works again. Thank you very much!
