### ISSUE TITLE
Bug: Running with live reload wont show the stop button

### ISSUE THREAD

**Issue by dtarnawsky** [ionic-team/vscode-extension#103]
If you enable Live Reload and do run > ios (or android) it will run the app but the stop button will disappear. Whenever you try to run a task it will be queued.

It should show the stop button, and even if a task is queued it should ask if you want to stop the live reload server.

**Comment by izyuumi** [comment]
I also have the same issue where the stop button disappears after a while. But, I got around when I noticed that <img width="203" alt="Screenshot20230406095220@2x" src="https://user-images.githubusercontent.com/36561306/230398812-50ea0d83-94c4-48c7-9ba2-43b77a089541.png"> was at the bottom of the window, and when I press it and press cancel on the popup, it works like the stop button.
However, it would be nice to be able to use the stop button directly in the extension pane.

**Comment by dtarnawsky** [comment]
This should now be fixed in 1.35.0
