### ISSUE TITLE
Run on Android and iOS Platforms Simultaneously

### ISSUE THREAD

**Issue by 3adeling** [ionic-team/vscode-extension#106]
I am using the Ionic VS Code extension and find it very useful. However, I have noticed that when I click on a new action in the extension window, I always receive a "Task Queued" message. Previously, I was able to run Android and iOS simultaneously, but now I must stop Android to run on iOS. I am unsure if this is intentional behavior or if there is a problem on my end.

**Comment by 3adeling** [comment]
It is not possible to build/sync while running on a platform

![image](https://user-images.githubusercontent.com/2550435/232736007-9249bb54-4745-491e-8802-04087f9d265b.png)

**Comment by dtarnawsky** [comment]
Hi @3adeling,

Version 1.36.0 has been released and it should allow you to run both iOS and Android simultaneously without queueing. For building and syncing, these are operations that are done whenever you run on iOS and Android so they will queue.
