### ISSUE TITLE
Ionic not working with Nx projects correctly

### ISSUE THREAD

**Issue by Swanzor** [ionic-team/vscode-extension#107]
I have a NX workspace with some of the projects being Capacitor projects (almost all of them are Angular projects). The projects show up correctly in the "NX PROJECTS" pane, but when click to select the project I would like to set, it doesn't show me any of the commands that are located in `project.json` file. It also does not give me all the ability to set the version number or any of those things. I also noticed that if I hover over the project I want to select if gives me a label that reads `undefined`.

In the VS Code output Ionic pane it gives me the following message:

```
[error] (node:26992) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
```

The environment is as follows: 

```
Windows 10
VS Code: 1.77.3
npm: 9.2.0
node: 18.12.1

Packages: 
        "@angular/animations": "~15.0.0",
        "@angular/cdk": "^15.0.3",
        "@angular/common": "~15.0.0",
        "@angular/compiler": "~15.0.0",
        "@angular/core": "~15.0.0",
        "@angular/forms": "~15.0.0",
        "@angular/google-maps": "^15.0.3",
        "@angular/platform-browser": "~15.0.0",
        "@angular/platform-browser-dynamic": "~15.0.0",
        "@angular/platform-server": "~15.0.0",
        "@angular/router": "~15.0.0",
        "@angular/service-worker": "~15.0.0",
        "@capacitor/android": "^4.6.1",
        "@capacitor/cli": "^4.6.1",
        "@capacitor/ios": "^4.6.1",
        "@capacitor/app": "^4.1.1",
        "@capacitor/core": "^4.6.1",
        "@capacitor/geolocation": "^4.1.0",
        "@capacitor/splash-screen": "^4.1.2",
        "@capacitor/status-bar": "^4.1.1",
        "@nrwl/angular": "15.4.4",
        "@nrwl/workspace": "15.4.4",
        "@nxext/capacitor": "^15.2.0",
        "nx": "15.4.4",
```

**Comment by dtarnawsky** [comment]
Hi @Swanzor ,

Are you able to share your project? You can send a zip of it to damian at ionic dot io.

The warning Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' is something you have configured on your windows machines (in environment variables) to bypass all network security. The usual reason for this is their IT Corp is trying to intercept all network traffic and use untrusted self-signed certificates. You should look for this setting in environment variables and remove it.

**Comment by dtarnawsky** [comment]
Hey @Swanzor ,

Version 1.36.0 was just released and it has a fix for NX 15 projects with Capacitor detection and detection of folders that have a project.json in them. Try it out and let me know if this resolves your issue.

**Comment by Swanzor** [comment]
@dtarnawsky 

> Are you able to share your project? You can send a zip of it to damian at ionic dot io.

Unfortunately, I am unable to share any source code.  I upgraded to the latest version and the issue seems to be resolved, but slight hick up is that if you switch from a project that is with Capacitor and one that does not have capacitor it still remembers the other project. Nothing breaking, but just trying to do my part it reporting this tiny issue.

Thank you for the swift answer.

**Comment by Swanzor** [comment]
> The warning Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' is something you have configured on your windows machines (in environment variables) to bypass all network security.

@dtarnawsky After setting this setting in my environment variables (note that this wasn't there before I created it) and then also setting the **Proxy Strict SSL** in VS Code to true (which it was by default), this still has not stopped that message from appearing. See images below.

![image](https://user-images.githubusercontent.com/61963904/233344160-eb31a20f-0739-4ee0-8e7a-74dab83f6c94.png)

![image](https://user-images.githubusercontent.com/61963904/233344191-b63494be-c36d-4e59-86b2-efc1f42741a1.png)

![image](https://user-images.githubusercontent.com/61963904/233344305-63e2cbe6-e26f-44e7-a5a8-6b16c09056f2.png)

> but slight hick up is that if you switch from a project that is with Capacitor and one that does not have capacitor it still remembers the other project

I know said in the previous comment that it was not breaking, but upon further investigation it does not actually switch correctly. The switch is slow, but the configurations don't actually update between projects. It only updates if I click the refresh button.

**Comment by dtarnawsky** [comment]
Hi @Swanzor ,

I've found that there are VS Code extensions that will set NODE_TLS_REJECT_UNAUTHORIZED to 0. You may need to identify other extensions that do this by removing them one by one, testing, then re-adding them. If there is an extension you can identify then we can take further action.

**Comment by Swanzor** [comment]
@dtarnawsky 

I was unable to replicate that message with any the extensions now (must have been fixed unintentionally in another version), but a new message started appearing when you refresh, switch projects, change configs, etc. that reads as follows: 

```
[error] Unable to run 'npm outdated'. Try reinstalling node modules (npm install)
```

This seems to be new. So I took your advice (believing it might be related to the previous problem) and I turned off all other extensions. It works with no issues. After the long process of going through roughly 66 extensions, only one gave me the issue and I suspect it must be the same culprit that caused the previous issue, which was the MySQL extension: 

```
Name: MySQL
Id: cweijan.vscode-mysql-client2
Description: Database manager for MySQL/MariaDB, PostgreSQL, SQLite, Redis and ElasticSearch.
Version: 6.4.3
Publisher: Weijan Chen
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-mysql-client2
```

No idea why this is causing an issue, but as a consequence I have disabled said extension in the workspace.

**Comment by dtarnawsky** [comment]
HI @Swanzor,

Thanks for finding the extension. I've filled a bug report on their repo:
https://github.com/cweijan/vscode-database-client/issues/834

The suspicious thing is that their repo does not have code that sets NODE_TLS_REJECT_UNAUTHORIZED to 0 but looking into their extension's installed binary it does have this code. This makes me suspicious that this is some form of malware.

**Comment by dtarnawsky** [comment]
Also, that error message will happen if you open a project that is missing its `node_modules` folder (ie you haven't run `npm install` yet). The end result is the extension won't be able to tell you what packages need updating. The extension will recommend installing node modules and if you do that the error goes away.

**Comment by Swanzor** [comment]
> The suspicious thing is that their repo does not have code that sets NODE_TLS_REJECT_UNAUTHORIZED to 0 but looking into their extension's installed binary it does have this code. This makes me suspicious that this is some form of malware.

@dtarnawsky Ok understandable. As a precaution I will remove this extension since the risk of malware is high. Rather not take the chance. 

> Also, that error message will happen if you open a project that is missing its `node_modules` folder (ie you haven't run `npm install` yet).

Are you talking about the root of the workspace or the project? As you usually don't run `npm install` on the  individual apps. Regardless, I will keep my eyes out if anything weird happens, in terms of running the extension in an Nx environment, however I think this has been sorted.

**Comment by dtarnawsky** [comment]
Hey @Swanzor , after reporting the issue for the MySql extension they fixed the problem in their latest update, so you shouldn't be getting that happening anymore (see https://github.com/cweijan/vscode-database-client/issues/834).

The `npm outdated` command is run at the root of the workspace, if there is a `node_modules` folder there, then the real error message the extension is getting can be found by going to `Help` > `Toggle Developer Tools`. Knowing what the error may be will helpful.
