### ISSUE TITLE
Nexus becomes unresponsive on scanning QR code

### ISSUE THREAD

**Issue by erikbaender** [ionic-team/vscode-extension#108]
Scanning the QR code from Nexus itself will always make the app unresponsive and show a black screen. The rest of the app seems to work fine though, as long as you use the stock camera app to scan the QR code and redirect to Nexus with the link.

Tested on Pixel 3a / Android 12

**Comment by dtarnawsky** [comment]
Thanks for the bug report @ebaender , 

This issue is fixed in 1.8 which was submitted to the stores today. This particular problem was related to Android and to fix we've added the plugin `@capacitor-community/barcode-scanner` and removed `phonegap-plugin-barcodescanner`.

**Comment by dtarnawsky** [comment]
Hi @ebaender ,

This issue should now be fixed in the v1.8 release which is available in both stores now.

Thanks for the bug report - Damian.
