### ISSUE TITLE
White Screen Appears on Launching iOS Project from VS Code Ionic Extension

### ISSUE THREAD

**Issue by 3adeling** [ionic-team/vscode-extension#110]
I am experiencing a problem with the Ionic extension in VS Code. Whenever I try to launch an iOS project using the extension, the screen appears blank and white. However, if I run the same application through Xcode, it functions flawlessly.

extension version: 1.38 and tried 1.39

**Comment by damiant** [comment]
Are you able to provide a sample project that does this?

One thing to try is to uncheck "Live Reload" in settings and try running.

**Comment by 3adeling** [comment]
Thanks @damiant for your support. the HTTPs option was enabled in the extension settings but the certificate was invalid. I got this error in xcode after deleting the ios project and build the ios project again

Error: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “10.249.1.88” which could put your confidential information at risk.

now the app works as expected after disabling HTTPs
