### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by Yvan-dev401** [ionic-team/vscode-extension#111]
bug: ionic plugin doesn't find my ionic project in my workspace

**Comment by dtarnawsky** [comment]
Hey @Yvan-dev401 ,

Can you provide a sample of your folder structure? and the mono-repo type you are using?
Access to a repo would help diagnose why it cant be found.

**Comment by dtarnawsky** [comment]
Hi @Yvan-dev401 ,

Without any info about your folder structure or which type of mono-repo you are using I cant help.
