### ISSUE TITLE
Unable to setPackageName for android

### ISSUE THREAD

**Issue by TheSoils** [ionic-team/vscode-extension#115]
I just start a ionic react app, then add android project and change bundle id.

Set Android Package Name to io.ionic.starter.ngd
[error] Unable to setPackageName for android: Error: Unable to load or parse gradle file: 错误: 找不到或无法加载主类 com.capacitorjs.gradle.Parse
原因: java.lang.ClassNotFoundException: com.capacitorjs.gradle.Parse

![DCF8F39C-1C67-4C20-99F8-FEF492FE8325](https://github.com/ionic-team/vscode-extension/assets/29093597/d6c6af40-7226-4eb1-80a4-ab5954709d0f)

m1 pro mac
node v16.19.0
Visual Studio Code 1.78.2
Ionic extention v1.43.2

**Comment by dtarnawsky** [comment]
Thanks @TheSoils , looks like a couple of files were missing that Trapeze needed. v1.44.1 should fix this issue (just released).
