### ISSUE TITLE
Redisplay ignored Recommendations

### ISSUE THREAD

**Issue by angelofan** [ionic-team/vscode-extension#116]
I didn't find a place to set the redisplay of ignored Recommendations.

**Comment by dtarnawsky** [comment]
Hi @angelofan ,

Thanks for the request, this feature has been added to v1.45.1 and you can get to it by clicking the `...` next to `Project` and choosing `Show Ignored Recommendations` as shown below:

<img width="1026" alt="show-ignored-recommendations" src="https://github.com/ionic-team/vscode-extension/assets/84595830/d111bc9b-9f5e-412c-ad03-e743c57f0ca5">
