### ISSUE TITLE
Plugin with id 'com.android.application' not found.

### ISSUE THREAD

**Issue by jensbroecher** [ionic-team/vscode-extension#118]
This happens every time, even when doing a fresh install of the VSCode Extension, create a new project, and then open it in Android Studio. I tried various solutions i found online but none worked.I upgraded to the latest Android Studio and now have the following problem:

> A problem occurred evaluating project ':app'.
> Plugin with id 'com.android.application' not found.

<img width="1440" alt="Screenshot 2023-05-26 at 16 45 59" src="https://github.com/ionic-team/vscode-extension/assets/6793646/8d37291c-fb53-46a4-9163-baf7082a0fdf">

**Comment by dtarnawsky** [comment]
Hey @jensbroecher , I'm wondering whether you did a `sync` before opening Android Studio?

If you missed that step then you would get an error like this.

If you have, and still have this problem then can you post a link to a sample repo with this error so I can compare it?

**Comment by jensbroecher** [comment]
Yes, i did the synch and everything imaginable. This happens even on a fresh install of the VS Code extension with a new project using the provided templates such as my-first-app and blank.

The problems started after installing:
Android Studio Flamingo | 2022.2.1 Patch 
Build #AI-222.4459.24.2221.9971841, built on April 19, 2023

**Comment by dtarnawsky** [comment]
Try going to `Settings` > `Build, Execution, Deployment` > `Build Tools` > `Gradle` and making sure the `Gradle SDK` is set to 17. Then close Android Studio and reopen the project.

Again, even if it is an empty new project, I'll need a sample repo with the error. This will help me determine if there is a problem with the project created, or it is your machine and its settings that is to blame.

**Comment by jensbroecher** [comment]
It's here: https://github.com/jensbroecher/Fixing-issue-with-ionic-vs-code-extension

<img width="1440" alt="Screenshot 2023-05-26 at 17 34 03" src="https://github.com/ionic-team/vscode-extension/assets/6793646/3cb159bf-3e6d-44f6-b96a-08b06a056839">

**Comment by dtarnawsky** [comment]
I get an error related to the package name you chose. I created a PR to fix it:
https://github.com/jensbroecher/Fixing-issue-with-ionic-vs-code-extension/pull/1

Essentially you cannot have a package name that includes just a number so I renamed `fridelivery.ionic.app.2023` to `afridelivery.ionic.app.v2023`. 

Try merging the PR and using that to see if you still get in any errors when building.

**Comment by dtarnawsky** [comment]
Fix done to prevent invalid package names when creating a project.
