### ISSUE TITLE
Invalid project type: angular-standalone (project config: .\ionic.config.json).

### ISSUE THREAD

**Issue by angelofan** [ionic-team/vscode-extension#119]
After using vscode-extension to generate the project, using `ionic g page new` to generate the page will throw an error:
```
Invalid project type: angular-standalone (project config: .\ionic.config.json).
```
Does `ionic-cli` not recognize `angular-standalone`?
ionic.config.json
```
{
   "name": "ionic-toast-color-test",
   "integrations": {
     "capacitor": {}
   },
   "type": "angular-standalone"
}
```
After manually changing `angular-standalone` to `angular`, everything works fine.

**Comment by angelofan** [comment]
I got this error last time I ran `ionic info`.

https://github.com/ionic-team/ionic-framework/issues/27567#issue-1731444883

**Comment by dtarnawsky** [comment]
Hey @angelofan ,

This error will occur if you are using Ionic CLI version 6 but run it against a project that was created with Ionic CLI version 7.

You'll need to update your CLI version using:
```bash
npm install -g @ionic/cli@7
```

You can also have the CLI installed locally with your project (and remove it globally). This allows you to have projects that are using different versions of the CLI.

Finally, you can find the version of the CLI you have installed by running `ionic -v` at the terminal.
