### ISSUE TITLE
Error inspecting project

### ISSUE THREAD

**Issue by ghost** [ionic-team/vscode-extension#12]
error inspecting project: Invalid Version: null

not sure what else you would need to debug but heres the package.json deps

  "dependencies": {
    "@agm/core": "^3.0.0-beta.0",
    "@angular/cdk": "^13.2.6",
    "@angular/common": "^13.2.6",
    "@angular/core": "^13.2.6",
    "@angular/forms": "^13.2.6",
    "@angular/platform-browser": "^13.2.6",
    "@angular/platform-browser-dynamic": "^13.2.6",
    "@angular/router": "^13.2.6",
    "@capacitor-community/firebase-analytics": "^1.0.1",
    "@capacitor/android": "3.4.3",
    "@capacitor/app": "^1.1.1",
    "@capacitor/browser": "^1.0.7",
    "@capacitor/core": "^3.4.3",
    "@capacitor/device": "^1.1.2",
    "@capacitor/filesystem": "^1.1.0",
    "@capacitor/geolocation": "^1.3.1",
    "@capacitor/haptics": "^1.1.4",
    "@capacitor/ios": "^3.4.3",
    "@capacitor/keyboard": "^1.2.2",
    "@capacitor/network": "^1.0.7",
    "@capacitor/project": "^2.0.0",
    "@capacitor/share": "^1.1.2",
    "@capacitor/splash-screen": "^1.2.2",
    "@capacitor/status-bar": "^1.0.8",
    "@capacitor/storage": "^1.2.5",
    "@ionic/angular": "^6.0.11",
    "@ngx-translate/core": "^14.0.0",
    "@ngx-translate/http-loader": "^7.0.0",
    "@scullyio/init": "^2.1.21",
    "@scullyio/ng-lib": "^2.1.21",
    "@sentry/angular": "^6.18.2",
    "@sentry/capacitor": "^0.4.4",
    "@sentry/tracing": "^6.18.2",
    "@types/facebook-js-sdk": "^3.3.5",
    "capacitor-resources": "^2.0.5",
    "cordova-plugin-ionic": "5.5.1",
    "cordova-plugin-whitelist": "^1.3.5",
    "cordova-resources": "^1.1.0",
    "prettier": "^2.5.1",
    "rxjs": "^7.5.5",
    "swiper": "^8.0.7",
    "tslib": "^2.3.1",
    "zone.js": "~0.11.5"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^13.2.6",
    "@angular-eslint/builder": "^13.1.0",
    "@angular-eslint/eslint-plugin": "^13.1.0",
    "@angular-eslint/eslint-plugin-template": "^13.1.0",
    "@angular-eslint/template-parser": "^13.1.0",
    "@angular/cli": "^13.2.6",
    "@angular/compiler": "^13.2.6",
    "@angular/compiler-cli": "^13.2.6",
    "@angular/language-service": "^13.2.6",
    "@capacitor/cli": "^3.4.3",
    "@capacitor/configure": "^2.0.0",
    "@ionic/angular-toolkit": "^6.1.0",
    "@tailwindcss/aspect-ratio": "latest",
    "@tailwindcss/forms": "latest",
    "@tailwindcss/line-clamp": "latest",
    "@tailwindcss/typography": "latest",
    "@types/google.maps": "^3.48.2",
    "@types/googlemaps": "^3.43.3",
    "@types/jest": "^27.4.1",
    "@typescript-eslint/eslint-plugin": "5.14.0",
    "@typescript-eslint/parser": "5.14.0",
    "autoprefixer": "^10.4.2",
    "cordova-res": "^0.15.4",
    "dotenv": "^16.0.0",
    "eslint": "^8.10.0",
    "eslint-plugin-import": "2.25.4",
    "eslint-plugin-jsdoc": "37.9.7",
    "eslint-plugin-prefer-arrow": "1.2.3",
    "jest": "^27.5.1",
    "jest-preset-angular": "^11.1.1",
    "ngx-tailwind": "^3.0.0",
    "postcss": "^8.4.8",
    "protractor": "~7.0.0",
    "tailwindcss": "^3.0.23",
    "ts-node": "^10.7.0",
    "typescript": "^4.5.5",
    "yargs": "^17.3.1"
  },

**Comment by dtarnawsky** [comment]
Hey @cherry-tom, is this a public project or one you could share privately? The extension uses the [capacitor configure](https://github.com/ionic-team/capacitor-configure) project for version detection and I think the problem may like there but would need access to source to investigate if you are willing to share.

**Comment by ghost** [comment]
it's private but willing to share. whats the email?

**Comment by dtarnawsky** [comment]
[email redacted] Taking this one private.

**Comment by dtarnawsky** [comment]
Hi @cherry-tom ,

Thanks for sharing the project and bug report. Using the error logged (Which are visible via Help -> Toggle Developer Tools) I was able to find that the error is caused when finding an npm package who latest version tag isn't a valid semver version number. The error is now correctly handled and your project should be able to be inspected now. Also, the stack trace showed you were using an insiders build of VS Code, I'm not sure if this is the reason for not being able to reproduce the problem.

In any case, version 1.1.1 of the extension is out and should correct your issue!
