### ISSUE TITLE
Extension runs/fails "npm outdated" after extension migrates project to pnpm as package manager

### ISSUE THREAD

**Issue by JPVan** [ionic-team/vscode-extension#120]
After following the following instructions from this link: [https://capacitorjs.com/docs/vscode/advanced](https://capacitorjs.com/docs/vscode/advanced)

> Other Features[​](https://capacitorjs.com/docs/vscode/advanced#other-features)
> Click the ... button next to Project to show a list of expermental features:
> Migrate from NPM to PNPM - Your project will be switched to use pnpm as its package manager.

the Ionic plugin repeatedly gives this error: 

> [error] Unable to run 'npm outdated'. Try reinstalling node modules (npm install)

Now that Ionic is working toward supporting pnpm (thank you!!) is there (or can there be) a way to specify which package manager the Ionic VS Code extension should use? Or at least get it to stop trying to run "npm outdated"? 

A related problem (I can write another issue if it would be helpful): The automatic migration from NPM to PNPM fails on windows apparently due to shell scripts assuming a Unix environment. 

Thanks!

**Comment by dtarnawsky** [comment]
Hey @JPVan ,

Thanks for the issue report. This issue has been resolved in v1.45.4 where `pnpm outdated` and `pnpm list` are now being used when pnpm is used as the package manager.

**Comment by JPVan** [comment]
Happy to help. Thanks for the quick resolution!
