### ISSUE TITLE
Feature Request: Capacitor Http 

### ISSUE THREAD

**Issue by mariomorenor** [ionic-team/vscode-extension#125]
It would be grest to test the Http Capacitor client. Actually doesn't have support.

**Comment by dtarnawsky** [comment]
You can use the API for Capacitor HTTP as described here: https://capacitorjs.com/docs/apis/http#example
It isn't possible to turn on the Capacitor HTTP by default though as you may be using [cordova-plugin-advanced-http](https://www.npmjs.com/package/cordova-plugin-advanced-http) which also does native HTTP.
