### ISSUE TITLE
Disable "New Project" Window on open

### ISSUE THREAD

**Issue by brodenbrett** [ionic-team/vscode-extension#127]
Hi, appreciate the extension.  

The latest update has caused a "New Project" tab to open without any way to disable this, a bit annoying when opening projects that aren't related to app work.  Is there a way to disable this feature or can one be added?

Thanks!

**Comment by dtarnawsky** [comment]
Hey @brodenbrett, this only occurs when you click on the Ionic logo for the extension right? or do you have another way of making this show?

**Comment by datenarbeit** [comment]
Hi @dtarnawsky,
I have the same issue on Mac. When VS Code was quitted, with no project window open, the new project assistant of ionic starts automatically, without any interaction. This does not happen, when I  quit VS with one or more project windows open.
Best!

**Comment by dtarnawsky** [comment]
Hi @datenarbeit / @brodenbrett ,

I'm having trouble reproducing the issue. I was wondering if you could record a video showing this happening?

**Comment by brodenbrett** [comment]
Sure @dtarnawsky, here's a video of what I mean.  This happens anytime I open a new window.
[Video](https://imgur.com/uCG3y5Z)

**Comment by dtarnawsky** [comment]
Ah interesting. Looks like you have the activity bar and welcome page hidden and are using Alt + R to open a recent project. The Ionic Extension also uses Alt + R to run a project but if there is no project it will open the new project window.

I'll see if I can check if there is a project to run when you press Alt + R and not show the new project dialog.

**Comment by dtarnawsky** [comment]
Version 1.72.2 is out and hopefully this fixes your issue. Please let me know!

The change is that using Alt+R will only work if the explorer pane is open, this should prevent the extension being activated and the new project page being displayed.

**Comment by brodenbrett** [comment]
@dtarnawsky Yup - this is fixed now!  Really appreciate your time and attention with what was an admittedly minor inconvenience.  Thanks again!

**Comment by brodenbrett** [comment]
@dtarnawsky Hi, I noticed this issue cropped up again for me even through I have my "Ionic: Run" hotkey removed.  

I believe I've narrowed down the cause.  It looks like it's happening because I have the "Ionic: My Project" view inside by primary sidebar instead of in the activity bar.  It looks like when "Ionic: My Project" is visible, the "New Project" tab is opened up automatically.  

Here's a video: https://streamable.com/x5ot75

If this is intentional, what do you think about adding a setting to disable this for use cases where devs split time between app and non-app work?

**Comment by dtarnawsky** [comment]
I've added a feature into v1.52 to allow you to only manually create new projects. Just check the option in "`Settings`" > "`Advanced`" > `"Manual New Projects"`. You will then only get the new project dialog when you select "`Ionic: New Project`" from the command palette.
