### ISSUE TITLE
IONIC panel stuck on "Please wait while inspecting project..." 

### ISSUE THREAD

**Issue by KyleQiLiu** [ionic-team/vscode-extension#128]
I just start using the IONIC vs code extension, after installing it, the IONIC panel just shows one line "Please wait while inspecting project...".

Am I missing any thing? Thank you!
![image](https://github.com/ionic-team/vscode-extension/assets/56694365/e8d56130-05c3-4b13-b8d9-874f2f308aab)

**Comment by dtarnawsky** [comment]
Hi @KyleQiLiu,

If you are able to share your project for me to look at you can send a zip file to damian at ionic.io. Otherwise, could you go to Help > Toggle Developer Tools in VS Code and see what errors may be coming up with you click the refresh button or go into the Ionic extension?

**Comment by welksonramos** [comment]
Hello I'm facing the same problem mentioned by @KyleQiLiu . Pressing the refresh button returns the following error
![image](https://github.com/ionic-team/vscode-extension/assets/5823027/a6baa481-fdf9-40b3-a9cf-43c01f1517c8)

**Comment by dtarnawsky** [comment]
Hey @welksonramos , are you are able to share your project for me to look at you can send a zip file to damian at ionic.io

**Comment by dtarnawsky** [comment]
Without a way to repro the issue I need to close this ticket.

**Comment by boyhax** [comment]
i have same problem for long time and i want to fix it now ,im sure it did appear first when i added firebase functions using firebase cli .i will send the repo if you still want.

**Comment by dtarnawsky** [comment]
Providing a repo that has the problem will mean I can get it fixed for you. You can send to damian at ionic.io

**Comment by boyhax** [comment]
ok but can explain better how to send it to damian you mean in the forum or discord ?

**Comment by dtarnawsky** [comment]
The email address damian at ionic.io . I'm spelling it out so that I dont get spam from bots.

**Comment by boyhax** [comment]
sorry really missed it. files send in email.
