### ISSUE TITLE
npm outdated is being called with a project that uses pnpm

### ISSUE THREAD

**Issue by oweitman** [ionic-team/vscode-extension#129]
In Version 1.48.0 the error still/again exists
if i downgrade to 1.45.4 the error is gone

`[error] Unable to run 'npm outdated --json'. Try reinstalling node modules.`

_Originally posted by @oweitman in https://github.com/ionic-team/vscode-extension/issues/121#issuecomment-1656811445_

**Comment by dtarnawsky** [comment]
Test steps to reproduce on Windows:
- create new project with ionic start with following settings
- no wizard, vue, project name test, starter template tabs
- after installtion is complete
- reopen vscode with new generated folder "test"
- if vscode is open, go to the ionic-extension
- in output window there is: [error] Unable to run 'npm outdated --json'. Try reinstalling node modules.

@oweitman, i tried this out on a Windows 10 machine with Node 16 and it worked fine. The call to `npm outdated --json` is something you can run yourself to see if it errors out. Also, in VS Code, click `Help` > `Toggle Developer Tools` and check in the console to see what errors are appearing. That will help diagnose why npm outdated is failing. I'll need more info about the problem to be able to resolve it.

**Comment by oweitman** [comment]
ok i found the solution.
it has to do with the node windows installation
In addition, there was a warning that I didn't pay attention to at first.
but after fixing it, the "outdated" message was gone

the fix was described here
https://stackoverflow.com/questions/72401421/message-npm-warn-config-global-global-local-are-deprecated-use-loc

the following problems were also fixed, 
- the wizard didnt use the directory that i opened for vscode
- if i want to select a different directory, then a message/toast is shown
"File system provider for C:%5CUsers%5Cmsowa is not available."
- and i cant select a different directory
- the name of the created directory is not test1, it is 'test1' (with the ‘ Char)

But i discovered something new. 
I'll open a new issue
