### ISSUE TITLE
Mono Repo Support for pnpm

### ISSUE THREAD

**Issue by reslear** [ionic-team/vscode-extension#13]
pnpm monorepo not working, only root

**Comment by dtarnawsky** [comment]
Thanks for the suggestion @reslear. Do you have a sample pnpm monorepo I could use to test with? I've used nx and lerna but would like to see if pnpm could be supported.

**Comment by reslear** [comment]
hi @dtarnawsky https://github.com/reslear/ionic-vue-pnpm-monorepo

**Comment by dtarnawsky** [comment]
Thanks for the repo @reslear, I took a little look at it and pnpm in general.  I've put this on the roadmap to include pnpm support (in general) as well as monorepo support. This may take a little bit of time to investigate.

**Comment by reslear** [comment]
@dtarnawsky use universal solutions like https://www.npmjs.com/package/ultra-runner , no source code to offer

**Comment by muuvmuuv** [comment]
This is, in general, not working for any Monorepo solution. We are working with [NX](https://nx.dev/angular/component) and [NXTend](https://nxtend.dev/docs/capacitor/overview).

**Comment by dtarnawsky** [comment]
Hey @muuvmuuv , NX is on the roadmap to support as well as its reasonably popular.

**Comment by dtarnawsky** [comment]
@muuvmuuv NX is now supported in the 1.3.0 pre-release of the extension. You can get this version by choosing "Install Pre-Release" as shown below:
<img width="481" alt="pre-release" src="https://user-images.githubusercontent.com/84595830/159170180-f94da330-45c5-4d64-8698-01295c179812.png">

I renamed this ticket to be specific to pnpm.

**Comment by dtarnawsky** [comment]
@reslear, pnpm and pnpm workspace support is now added to version 1.5.11 which you install the **pre-release**. This version is expected to go out to all early next week. If you find any issues with the pre-release do not hesitate to connect back up, and thanks for providing the sample repo!
