### ISSUE TITLE
Trying to use the Run Android feature, but command is returning an error for JAVA_HOME

### ISSUE THREAD

**Issue by plasmy** [ionic-team/vscode-extension#132]
When I run the command, I get the following:

<img width="864" alt="Screenshot 2023-08-19 at 5 28 52 PM" src="https://github.com/ionic-team/vscode-extension/assets/5615530/182d27c8-324e-43aa-bc11-b15e4339c653">

However, running the same command on terminal works perfectly.

**Comment by dtarnawsky** [comment]
You can set the location of JAVA_HOME in Settings > Advanced.

The reason you are getting this error is the VS Code may use a different shell when running node processes than the terminal shell you use. If they dont have the same environment variables you will get this error.
