### ISSUE TITLE
Feature Request: Extension should be able to Rename Application. 

### ISSUE THREAD

**Issue by Saqib92** [ionic-team/vscode-extension#133]
There should be an option to Rename Complete application using VS code extension.

**Comment by dtarnawsky** [comment]
Hi @Saqib92 ,

You can rename your application through `Configuration` > `Properties` > `Display Name`. This will allow you to rename what is displayed on the home screen of the phone. You can also alter the bundle ID as well or version information. Was there something else you wanted to rename?

**Comment by Saqib92** [comment]
> 

Wow, I missed it. super easy way to change the App name. I had to remove platform and then re-add them to change name. sometimes I have custom native code which I had to rewrite as well. This is really good feature.
