### ISSUE TITLE
Capacitor migration clicking nothing happens.

### ISSUE THREAD

**Issue by rashnk** [ionic-team/vscode-extension#139]
I'm working on an old cordova project and want to migrate to capacitor, however the extension is not working.

Clicking on Add capacitor integration does nothing, tried reinstalling extension several times.

https://github.com/ionic-team/vscode-extension/assets/12730428/4963c13c-1a93-48eb-b835-9fa7041193ac

**Comment by dtarnawsky** [comment]
Are you able to supply a zip of your project so that I can reproduce the issue?

**Comment by rashnk** [comment]
first let me try in a new cordova project, I will update you thank you.

**Comment by rashnk** [comment]
same issue in new Cordova project created.
https://github.com/ionic-team/vscode-extension/assets/12730428/82d60813-fed0-4bda-9b70-e60d249c3626

**Comment by rashnk** [comment]
cordava project zip file [cap-migrate-test.zip](https://github.com/ionic-team/vscode-extension/files/12883946/cap-migrate-test.zip)

**Comment by dtarnawsky** [comment]
Just tested this out on a Mac and it adds the Capacitor integration without an issue. I'll try it on Windows shortly, but you could see if any errors occur by clicking `Help` > `Toggle Developer Tools` and seeing if there are any errors logged.

**Comment by dtarnawsky** [comment]
This worked fine with Windows as well. As it is just attempting to run a node command my guess is that the node installation is corrupt. Uninstall NodeJS from Windows (delete from `c:\program files` if you need to) then reinstall and try again.

**Comment by rashnk** [comment]
Look like the Do not disturb mode was on, that is the reason it does not popup anything when click,

https://github.com/ionic-team/vscode-extension/assets/12730428/bd336f84-48e8-419b-be0a-c1230dc0b0df
