### ISSUE TITLE
public-host option added incorrectly when used with the https option.

### ISSUE THREAD

**Issue by ahmadtawakol** [ionic-team/vscode-extension#140]
If I use the external address option with live reload, the `--public-host` option gets appended to the end of the command, which is fine except when I also turn on the `Use HTTPS` option. Then the `--public-host` option gets added to the very end, after the `--`, where it then has no effect.

This is what runs when I click on Run:
`npx ionic cap run ios --target=00008130-000E65400821401C  --livereload --external --no-sync --ssl -- --ssl-cert=<server.crt> --ssl-key=<server.key> --public-host=192.168.0.88`

This is what it is supposed to look like:
`npx ionic cap run ios --target=00008130-000E65400821401C  --livereload --external --no-sync --ssl --public-host=192.168.0.88 -- --ssl-cert=<server.crt> --ssl-key=<server.key>`

**Comment by dtarnawsky** [comment]
Thanks for the bug report @ahmadtawakol , I've fixed this issue in 1.53.0 of the extension. Please give it try and let me know if you have any further issues.

**Comment by ahmadtawakol** [comment]
Can confirm that it now works correctly. Thank you!
