### ISSUE TITLE
"command 'ionic-official.refresh' not found" when trying to refresh vscode extension

### ISSUE THREAD

**Issue by alexandermorgan** [ionic-team/vscode-extension#141]
I'm a long-time capacitor user but new to the ionic vscode extension. I haven't been able to get any of the recent versions of the extension to start. From version 1.39.4 to the current one (1.54.0), they all get stuck with the message "Please wait while inspecting project..." and nothing happens. Trying to hit the refresh button gives the error: "command 'ionic-official.refresh' not found".

This seems related #128 and #59 but the latter was reported fixed in version 1.12.1 back in November 2022. Version 1.38.0 works. I don't think this has anything to do with my project because I have the same issue when opening the ionic extension in a new empty vscode window. I'm running this on an M1 macbook air, vscode version 1.68.1. Thanks.

**Comment by dtarnawsky** [comment]
Hi @alexandermorgan ,

I'd love to be able to get to the bottom of your issue. First, are you able to update to a later version of VS Code? I'm using 1.83.1 of VS Code on my MacBook M1 with no trouble, so perhaps 1.68.1 is a little old.

Next, what version of node do you have installed? Also do you use nvm, volta or another node versioning tool?

**Comment by alexandermorgan** [comment]
Thanks, I didn't realize my VSCode was out of date. I still had my vscode in the downloads folder which meant that I couldn't update it. So I moved it to the applications folder, updated, and then updated the ionic extension to 1.54.0 and now it's working. Thank you!
