### ISSUE TITLE
Failure to parse `project.json` with comments

### ISSUE THREAD

**Issue by SamuelT-Beslogic** [ionic-team/vscode-extension#142]
`project.json` is a "jsonc"/"JSON with Comments" file. Comments should be supported and simply ignored. Angular supports it, NX supports it.

Comments are important to explain why certain configurations are as such.

![image](https://github.com/ionic-team/vscode-extension/assets/84519004/fbbdf74a-5a4c-4be7-b448-6b71713d9cc3)

**Comment by dtarnawsky** [comment]
This issue is now fixed in version 1.55 released today.
