### ISSUE TITLE
Configuration changes not applied everywhere

### ISSUE THREAD

**Issue by danbaechtold** [ionic-team/vscode-extension#143]
When using the Extension to change the "Bundle Id" (under Configuration - Properties), the following files/values are not updated:

- app\capacitor.config.json ("appId")
- app\android\app\src\main\res\values\strings.xml ("package_name" and "custom_url_scheme")

Note: I have the Ionic/Capacitor app in a subfolder (/app).

**Comment by dtarnawsky** [comment]
Hi @danbaechtold ,

Version 1.57.0 of the extension will now alter the `capacitor.config.json` and `strings.xml` to match.

Keep in mind that `capacitor.config.json` has no effect unless you are recreating your ios/android project (which you shouldn't be doing). The `package_name` is also not used as changing it doesn't affect the display name for the application. Finally, updating the `custom_url_scheme` will also not affect the app as this is overwritten by Capacitor.
