### ISSUE TITLE
The plugin does not read the 'pnpm-workspace' file to detect the 'ionic-app' in the 'apps' folder.

### ISSUE THREAD

**Issue by Roberto4091** [ionic-team/vscode-extension#144]
Hello, I'm using the latest version of the plugin v1.55.1 in a monorepo that works with pnpm, but the plugin can't find the app. From what I can see, it's reading the root's package.json file. I'm attaching screenshots

pnpm-workspace.yaml
```
packages:
  - 'apps/*'
  - 'packages/*'

```

Root structure 
<img width="300" alt="Screen Shot 2023-10-25 at 12 23 01 AM" src="https://github.com/ionic-team/vscode-extension/assets/25492879/e1ccf644-99bc-4f04-ac9e-d222bccbf8b1">

App structure 
<img width="300" alt="Screen Shot 2023-10-25 at 12 23 14 AM" src="https://github.com/ionic-team/vscode-extension/assets/25492879/41e65c65-16f1-4666-940f-235710cba46d">

Result in plugin 
<img width="754" alt="Screen Shot 2023-10-25 at 12 23 33 AM" src="https://github.com/ionic-team/vscode-extension/assets/25492879/bdec9841-80fc-496f-a699-c486d3c26772">

I also used the multi-workspace structure provided by Visual Studio Code, as I saw in the plugin documentation that it is supported, but the result was the same.

**Comment by dtarnawsky** [comment]
Thanks for the bug report @Roberto4091, the problem seems to be the single quotes ' in the folder names in `pnpm-workspace.yaml`. The extension was only supporting " double quotes or no quotes. In v1.56.0 the problem is fixed.
