### ISSUE TITLE
Specify Ionic Cli path

### ISSUE THREAD

**Issue by francescodoffizi** [ionic-team/vscode-extension#147]
I'm encountering an issue when running an older project due to Npm < 14 deprecation.

I've noticed that the vscode-extensions, even though they correctly load the nvm version, use the vscode-extension ionic-cli instead of the global or local one. I'm unable to locate a configuration parameter to specify the ionic-cli path or a specific version.

Is there a method to force the plugin to execute a specific version of ionic to maintain compatibility with specific project npm/node versions?

**Comment by dtarnawsky** [comment]
The extension runs `npx ionic [commands]` which will use the local Ionic CLI if it is in the project's `node_modules` (double check you have `@ionic/cli` in your `package.json`). Do you have a sample repo where it doesn't find this?

**Comment by dtarnawsky** [comment]
Closing as the extension should be using the correct CLI. Note: Projects using Ionic CLI < v3 are not supported
