### ISSUE TITLE
Cannot find Angular "super" template 

### ISSUE THREAD

**Issue by baffioso** [ionic-team/vscode-extension#15]
Tried to create "super" project
<img width="244" alt="image" src="https://user-images.githubusercontent.com/7534153/157965542-9c481243-4f52-467e-a59e-7c1de077664d.png">

But get this error
<img width="457" alt="image" src="https://user-images.githubusercontent.com/7534153/157965141-517f6fb6-42c3-4b3f-84e0-cf41e374fe82.png">

**Comment by dtarnawsky** [comment]
Thanks for the bug report @baffioso ! 

I can see where the issue is, this template should get filtered out as it was for Ionic 2/3. Expect a fix for this in the 1.1.2 release.

**Comment by dtarnawsky** [comment]
@baffioso, 1.1.2 is released so i'll close out this issue.
