### ISSUE TITLE
Angular Switch to ESBuiild. No longer possible to work in Live Reload

### ISSUE THREAD

**Issue by alexanderdomrachev** [ionic-team/vscode-extension#150]
Cases after "Switch to ESBuiild":

Run -> Android

App does not deploy or open automatically on device. It is no longer possible to work in Live Reload on the device. There is no alternative way to open the application in "--watch or --serve" mode on device.

Run -> Web

After launching the application also does not open automatically in the browser tab.

<img width="1226" alt="Monosnap package json — demotv-ionic-capacitor 2023-12-27 17-54-35" src="https://github.com/ionic-team/vscode-extension/assets/17156410/21f55943-9a02-4a5b-9911-b2169416ca65">

**Comment by alexanderdomrachev** [comment]
After rolling back to the old builder everything became normal.

<img width="903" alt="image" src="https://github.com/ionic-team/vscode-extension/assets/17156410/7aee0f62-4917-47e8-ba23-c1c52908bcf4">

**Comment by dtarnawsky** [comment]
This was an issue with the Ionic CLI and version 7.20 of the CLI was released to address this issue. Version 1.65 of the extension will recommend updating your Ionic CLI to at least 7.20 to fix the live reload issue.
