### ISSUE TITLE
Can't log into Ionic while in codespaces

### ISSUE THREAD

**Issue by gvilomar** [ionic-team/vscode-extension#151]
When I try to log into Ionic while in codespaces, it opens a browser window on localhost:8123 but I get an error stating that it couldn't reach the page and with an additional message of "localhost refused to connect."  

<img width="582" alt="Screenshot 2023-12-29 at 10 07 56 AM" src="https://github.com/ionic-team/vscode-extension/assets/19170047/d3d2eb26-dc30-4119-bbc4-2c5897f9e58b">

When I go the output screen of vscode, I get this error:

> [[40mINFO[49m] During this process, a browser window will open to authenticate you. Please leave this process running until authentication is complete.
> 
> --confirm: Open the browser to log in to your Ionic account? Yes
> [Error: ENOENT: no such file or directory, open '/home/codespace/.vscode-remote/extensions/ionic.ionic-1.64.0/node_modules/@ionic/cli/assets/oauth/success/index.html'] {
>   errno: -2,
>   code: 'ENOENT',
>   syscall: 'open',
>   path: '/home/codespace/.vscode-remote/extensions/ionic.ionic-1.64.0/node_modules/@ionic/cli/assets/oauth/success/index.html'
> }

I get the same error on different browsers.

**Comment by dtarnawsky** [comment]
This should be "fixed" in 1.62.2. Codespaces does not have the ability to open a browser and redirect back unfortunately, so this functionality cannot be implemented. The fix will now give you a message and allow you to continue anonymously.
