### ISSUE TITLE
Can't loggin from VS Code ionic plugin

### ISSUE THREAD

**Issue by franjac** [ionic-team/vscode-extension#155]
When clic loggin button goes to http://localhost:8123/?code=8WQc2KrVZm9UyZ0XIeqD6DKCIthXC4kG147CPuLXfBhdRG9T 
but nothing listening on 8123 port.

**Comment by navalex** [comment]
+1
Here is console output:

```bash
--confirm: Open the browser to log in to your Ionic account? Yes
[Error: ENOENT: no such file or directory, open '/Users/alexandrenavaro/.vscode/extensions/ionic.ionic-1.65.2/node_modules/@ionic/cli/assets/oauth/success/index.html'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/alexandrenavaro/.vscode/extensions/ionic.ionic-1.65.2/node_modules/@ionic/cli/assets/oauth/success/index.html'
}
```
I tried to check the path, and it seems `assets` folder is missing in `.vscode/extensions/ionic.ionic-1.65.2/node_modules/@ionic/cli/`
I guess it moved somewhere else ?

**Comment by Matthewenderle** [comment]
I have this issue as well on the latest version. I installed version 1.60.0 and was able to login.

**Comment by finallyblueskies** [comment]
+1

**Comment by dtarnawsky** [comment]
Hey all, I'm currently looking into this however in the meantime if you call `ionic login` at the command prompt and login that way, then restart VS Code it will be logged in and you wont see the login page.

**Comment by dtarnawsky** [comment]
v1.66 should have this issue fixed.

**Comment by JPFarber55** [comment]
I have v1.66 and have the same problem.
`[Error: ENOENT: no such file or directory, open '/home/user/.vscode-server/extensions/ionic.ionic-1.66.0/node_modules/@ionic/cli/assets/oauth/success/index.html'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/user/.vscode-server/extensions/ionic.ionic-1.66.0/node_modules/@ionic/cli/assets/oauth/success/index.html'
}
`

**Comment by dtarnawsky** [comment]
Now that 1.67 is out you'll find that you no longer need to login to the extension to use it. It can detect if you are logged via the CLI.
