### ISSUE TITLE
Firewall blocking connection between Windows and Nexus App - real device with wifi

### ISSUE THREAD

**Issue by websystems-dev** [ionic-team/vscode-extension#156]
I'm debugging an ionic app with Visual Code and a real device on the same network.
With DISABLED Firewall: everything is ok and the app "Nexus Browser" connects to local server on my PC.
With ENABLED Firewall there is no connection at all.

And I cannot bypass this block even if I add a generic rule "permit all" with any source, any destination, any protocol, any port, etc...
Even if I choose "allow" as default behavior for all inbound and outbound connection, it does not work.

The only way to make it connect is to DISABLE the entire firewall. What I am missing?

(OS: Windows11)

**Comment by dtarnawsky** [comment]
The VS Code extension does a UDP broadcast on port 41234 to announce when it has an app that is being served up. Nexus Browser listens on the network for this UDP broadcast and will auto-launch the app.

It sounds like UDP is blocked, so you would need to manually type in the IP address and port into the Nexus Browser (eg `192.168.0.15:4200`). You can test that there is network connectivity between your phone and computer by opening iOS Safari and typing in the url of the dev web server.

**Comment by dtarnawsky** [comment]
Hey @websystems-dev , I assume you were able to get this working by unlocking UDP port 41234. I'll close out this issue.
