### ISSUE TITLE
Nexus Browser: not responding

### ISSUE THREAD

**Issue by TheSoils** [ionic-team/vscode-extension#158]
ionic vscode extension plugin: v1.70.0
nexus: v1.17.8
ios: 17.3.1

nexus browser on iOS does not work, it show ***(local network address) is not responding after scan qrcode.
the website can be browse by safari.
the nexus does not ask permission  for local network.
nexus can browse apple.com 

![IMG_9857](https://github.com/ionic-team/vscode-extension/assets/29093597/fa19c972-067b-43a9-ac12-cfbbab03f555)
![IMG_9858](https://github.com/ionic-team/vscode-extension/assets/29093597/f0ab7b03-8fb7-42d2-9a9d-b01df2011d0c)
![IMG_9859](https://github.com/ionic-team/vscode-extension/assets/29093597/3fb381eb-01ac-4f39-8da3-7c68c6386daf)
![IMG_9861](https://github.com/ionic-team/vscode-extension/assets/29093597/037ad071-cc5c-475a-b90b-a16b271657b7)

**Comment by dtarnawsky** [comment]
Thanks for the bug report. This is working locally here and Nexus will usually prompt for local network access as well. Would you be able to delete the app completely and reinstall to see if the problem disappears.

Also, if there is anything about your Wifi network that might be unusual that would help me reproduce the issue then let me know (maybe a VPN, multiple network addresses etc).

**Comment by dtarnawsky** [comment]
Closing as Nexus Browser is working as expected and I need more information to reproduce an issue.
