### ISSUE TITLE
[FR] Make Ionic Commands Searchable/Executable from VSCode Command Palette

### ISSUE THREAD

**Issue by sultanmyrza** [ionic-team/vscode-extension#159]
Recently, I've been using the VSCode extension "Ionic", which offers useful commands such as "sync" and "open in Xcode". For example, to open a project in Xcode, I currently have two options:

- I can open the terminal and type "npx cap open ios".
- Alternatively, I can navigate to the Ionic extension tab and click the "Open in Xcode" button.

It would greatly enhance the user experience if I could access the "open in Xcode" functionality directly from the VSCode command palette. This would align with the convenience offered by other extensions. For instance, the "Copilot" extension allows me to initiate an inline chat by simply typing "start inline" in the command palette and hitting enter. The command palette proves to be particularly handy when I don't want to remember specific shortcuts but prefer to type the action's name directly.

<img width="1512" alt="Screenshot 2024-02-25 at 7 21 19 PM" src="https://github.com/ionic-team/vscode-extension/assets/12681781/8d89be4d-010b-4d84-b46a-5dff77816178">

**Comment by dtarnawsky** [comment]
Hey @sultanmyrza , this should be available in the next release of the extension (hopefully this week).

**Comment by dtarnawsky** [comment]
Hi @sultanmyrza, a bunch of commands were added to the command palette in v1.80. If you see any command missing that you would like please open a new issue and I can take a look.
