### ISSUE TITLE
Ability to copy code snippets to clipboards and navigate to file references

### ISSUE THREAD

**Issue by marlon-ionic** [ionic-team/vscode-extension#16]
For menu items that provide code snippets and/or mention specific project files, there should be options to:

- copy the suggested code to the system clipboard
- open any referenced file in a new tab.

As an example, I saw the following 'Recomendation':

>The android preference AndroidXEnabled should be true. Add `<preference name="AndroidXEnabled" value="true" />` to `<platform name="android">` in config.xml

It would be more convenient to give users the ability to copy the pertinent block of code by clicking a button. Highlighting the text in the info popup isn't quite as intuitive. Since there's a reference to the specific file (config.xml), it would also be great to have a button that navigates to the file.

**Comment by dtarnawsky** [comment]
Hey @marlon-ionic , for these types of messages I've usually been lazy and hadn't written a migration to fix the problem. So, in 1.2.1 I've fixed this particular problem, when a Cordova project where `AndroidXEnabled` is not true it will have a `"Fix config.xml"` button which applies the fix to `config.xml`.
