### ISSUE TITLE
Configuration -> Statistics command fails

### ISSUE THREAD

**Issue by shpasser** [ionic-team/vscode-extension#161]
I have a vue-vite Ionic project. While running `Configuration -> Statistics` command via the plugin I get the following output:

```
[Ionic] Building for production with Sourcemaps...
[error] export NODE_OPTIONS="--max-old-space-size=8192" && npx vite build --prod && npx cap copy Failed
[Ionic] Analyzing Sourcemaps...
[Ionic] Launched project statistics window.
```

<img width="445" alt="Screen Shot 2024-03-18 at 8 48 15" src="https://github.com/ionic-team/vscode-extension/assets/4275204/d18907e8-430c-4003-831c-2695b0985452">

It looks like `vite build` does not have a `--prod` option.

Please help.

**Comment by dtarnawsky** [comment]
Hey @shpasser ,

This should be fixed in the latest version. Can you give it a try and let me know how it goes.

**Comment by shpasser** [comment]
Thanks it works now.
