### ISSUE TITLE
Help Tool in format Ionic standalone components

### ISSUE THREAD

**Issue by diendv** [ionic-team/vscode-extension#162]
help me when importing ionic tags in .html file then automatically add component in .ts file
Exam: in file .html key input ion-content after auto add IonContent in file .ts, that I don't need to run "Migrate to Ionic standalone components."

**Comment by dtarnawsky** [comment]
I'm trying to work out what you mean here. I think what you are after is for the extension to automatically add an IonContent import in your .ts file without using standalone components?

I'm wondering if you could explain the issue in more detail?

**Comment by diendv** [comment]
yes I need it, meaning when I import ion-text in .html file then in .ts file it will automatically add for me IonText without me having to enter in "import" and "imports" of "@Component" anymore.

**Comment by dtarnawsky** [comment]
That is how it should work - as soon as you hover over the red line under `ion-text` it will add to the imports.
Does your component have `standalone` set to `true`?
Are you using Angular 17?
Also, what version of the Ionic extension are you using?

**Comment by diendv** [comment]
I am using angular 17.
"Component" I have set up as standalone .
I am using ionic v.1.81.3 extension version.

"That is how it should work - as soon as you hover over the red line under ion-text it will add to the imports.". Can you walk me through or take a photo of an example so I can visualize how you use it

**Comment by dtarnawsky** [comment]
Here's a YouTube video demonstrating how it works: [https://www.youtube.com/watch?v=NaHPVpXrAlo&t=8s](https://www.youtube.com/watch?v=NaHPVpXrAlo&t=8s)

If you can provide some example code that shows this not working we can certainly debug it to find out why its not working for you.

**Comment by diendv** [comment]
I have file test.ts with code below:
import { Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-test',
  templateUrl: './test.page.html',
  styleUrls: ['./test.page.scss'],
  standalone: true,
  imports: [FormsModule]
})
export class TestPage implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}


And file .html
<ion-header [translucent]="true">
  <ion-toolbar>
    <ion-title>test</ion-title>
  </ion-toolbar>
</ion-header>

<ion-content [fullscreen]="true">
  <ion-header collapse="condense">
    <ion-toolbar>
      <ion-title size="large">test</ion-title>
    </ion-toolbar>
  </ion-header>
</ion-content>

I tried entering it like the video you sent but it didn't work
![screenshot_1711123335](https://github.com/ionic-team/vscode-extension/assets/37656052/c22b6783-f770-486f-adf8-05f36c4b1808)
![screenshot_1711123220](https://github.com/ionic-team/vscode-extension/assets/37656052/20b20942-20aa-4753-a795-f72deaeb12da)
![screenshot_1711123207](https://github.com/ionic-team/vscode-extension/assets/37656052/b2714bbd-e495-48d1-ae36-3af5a32eac11)

**Comment by diendv** [comment]
This makes me really tired, I don't understand why. Do I have to create an ionic project from visual studio code?

**Comment by dtarnawsky** [comment]
Closing as I do not believe this is a reproducable issue. One thing to verify is that the Angular Language Service is installed in VS Code - without this VS Code is not going to report missing import and therefore the extension is not going to fix the imports.
