### ISSUE TITLE
Is vscode-extension closed-source?

### ISSUE THREAD

**Issue by jemdiggity** [ionic-team/vscode-extension#163]
Hello, the repository shows as empty so is this project closed-source?
I’m using your extension with a nuxt/ionic stack targeting web & mobile in a pnpm workspace monorepo. When the extension works, it’s great but when it doesn’t it’s difficult to figure out why besides diff’ing a set of code that works and one that doesn’t.
Thanks!

**Comment by dtarnawsky** [comment]
Hi @jemdiggity ,  the extension is closed source. If you can send your code (or a representative sample) to damian@ionic.io then I can investigate why your project may not be working. The extension has to work for dozens of different monorepos and project styles so there is bound to be ones it is not expecting.

**Comment by dtarnawsky** [comment]
Closing this issue out as I need a sample project to work with.
