### ISSUE TITLE
Monorepo support for Nx

### ISSUE THREAD

**Issue by dtarnawsky** [ionic-team/vscode-extension#17]

**Comment by dtarnawsky** [comment]
Released as part of 1.3.0

**Comment by ghost** [comment]
I'm receiving the following error when an Ionic app is split into libs using Nx.
"The "path" argument must be of type string. Received an instance of Object"
example: https://github.com/cherry-tom/nx-ionic-angular

**Comment by dtarnawsky** [comment]
Thanks for the repo @cherry-tom , looks like for NX the workspace.json can either have simple folders or complex objects that have a root property with the folder name. So, I've fixed this in v1.4.3 and it will correctly read the list of NX projects to get past that error.
