### ISSUE TITLE
New Project Flow > Options selected not visible in high contrast theme

### ISSUE THREAD

**Issue by gdamalis** [ionic-team/vscode-extension#170]
## Actual behavior
Pre-condition: Set VS code theme to `Dark High Contrast`
When dev clicks on `Start New Project` a window is displayed with configuration options, when the dev clicks on any button, the selection is not marked and dev is not getting feedback of what are the selected options.

I've recorded the experience and demo how it looks with other theme:
https://www.loom.com/share/732f6e938eac488b83fbc8c8988ab8ea

**Comment by dtarnawsky** [comment]
Hey @gdamalis , thanks for the bug report. This should now be fixed in v1.85.4 released today. It should also work better using Light High Contrast as well.
