### ISSUE TITLE
Support for other shells 

### ISSUE THREAD

**Issue by ramonsan** [ionic-team/vscode-extension#18]
I am on MacOS 12.2.1 , and since macOS 10.15 zsh is de default shell, replacing bash.

When I run any command with this extension an error pops ups saying `/bin/sh` not found npx. Integrated terminal of VS Code works fine with zsh shell.

There is no options in the extension configuration to set an alternative shell.

Should be interesting to use the integrated terminal of VS Code, or add an option in configuration to set the default shell to use.

> OS version: MacOS 12.2.1
> VS Code version: 1.65.1
> Ionic version: 6.18.1
> Capacitor version: 3.1.2
> Ionic extension version: 1.2.2
> Node version: 14.17.0

**Comment by dtarnawsky** [comment]
Hi @ramonsan, what is the exact error message?
What version of node do you have installed?

The reason I ask is that all commands are run using node's `child_process.exec`. If a version of Node cannot be found you'll get errors.

**Comment by ramonsan** [comment]
Node version is v14.17.0.

When I try run any command, it says

``` 
[Ionic] Running on Web...
> npx ionic serve
/bin/sh: npx: command not found
``` 

But npx works fine on zsh and bash shells on integrated terminal.

**Comment by dtarnawsky** [comment]
@ramonsan Can you run `echo $path` on the command line and report back your path. If you have an older version of node that did not include `npx` then you would get this error message. `npx` came with `npm` version 5.2.0 and after. You can install a later version of npm using: `npm install -g npm`. You can report back the version of npm with `npm -v`.

**Comment by ramonsan** [comment]
`npm` is installed, and `npm -v` works in both bash and zsh.`npm` version is 8.4.1.

My path:
``` 
/usr/local/google-cloud-sdk/bin /Users/ramonsan/.nvm/versions/node/v14.17.0/bin /Users/ramonsan/Library/Android/sdk/build-tools/30.0.3 /Users/ramonsan/Library/Android/sdk/emulator /Users/ramonsan/Library/Android/sdk/platform-tools /Users/ramonsan/Library/Android/sdk/tools/bin /Users/ramonsan/Library/flutter/bin/ /usr/local/sbin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/share/dotnet /Users/ramonsan/.dotnet/tools /Library/Apple/usr/bin /Library/Frameworks/Mono.framework/Versions/Current/Commands
```

**Comment by dtarnawsky** [comment]
It's quite challenging to reproduce this issue. @ramonsan could you try something for me. Remove your node_modules using `rm -rf node_modules` then if you look in the VS code extension it should give a recommendation of "Install Node Modules". Click that and it should run `npm install` . If this works when we know that the path for `npm` is good and it is `npx` that is missing.

(Sorry for the back and forth, its challenging to identify the cause of the issue. I have a hunch it has to do with nvm but not sure yet).

**Comment by ramonsan** [comment]
I solved it changing the default shell of npm scripts to zsh.

`npm config set script-shell /bin/zsh`.

Now, all commands run smoothly.

**Comment by dtarnawsky** [comment]
Awesome @ramonsan . I was wondering if you had an alternate shell set previously? Running `npm config get script-shell` would return what was set. The reason I ask is that for a normal setup the `script-shell` will be `null` and it should just work. But if your `script-shell` was set to something else then it is something I can detect in the extension and offer advice to anyone who runs into this.

**Comment by ramonsan** [comment]
`script-shell` was `null` before I set zsh. Extension was using `/bin/sh` by default with this configuration.

I have `$PATH` set in .bashrc, and .zshrc is sourcing .bashrc.

What I have thought is maybe there is a specific zsh configuration in .bashrc that I have added later, being not valid for bash, causing it to not read the config file correctly. In this case it would be my fault.
