### ISSUE TITLE
Support for multiple environments

### ISSUE THREAD

**Issue by colin-om** [ionic-team/vscode-extension#19]
It would be great to have the ability to select different configurations/environments when building the app, similar to the 'select a device' menu when running on iOS or Android.

**Comment by dtarnawsky** [comment]
Could you elaborate a little @colin-om? Do you mean for Angular based projects where you have a prod and dev build?

**Comment by colin-om** [comment]
Hi @dtarnawsky, exactly that yes, sorry I thought I mentioned Angular in the issue but looks like I missed it. In the angular.json you can have any number of different build configurations with fileReplacements, and this would be great to have access to when building from the plugin, as it could be much more than just dev and prod builds https://angular.io/guide/build#configure-target-specific-file-replacements

**Comment by dtarnawsky** [comment]
Hey @colin, this feature is now available in the 1.3.2 Pre-release available now. An icon next to Build appears with three dots (...) that allows you to select the type of build to create. It grabs the build configuration from your `angular.json`.

1.3.2 should be available to the public in a day or two assuming no major issues are found.
