### ISSUE TITLE
npx: command not found

### ISSUE THREAD

**Issue by timeisgolden** [ionic-team/vscode-extension#21]
Hello, Guys!!!
When I select 'Run on Web', I am getting the following error.
<img width="1536" alt="image" src="https://user-images.githubusercontent.com/54345950/159869866-d8579cf3-81db-46e6-911c-9ee8c6a9efeb.png">
My project is based on Capacitor.
Do you have any suggestions?

**Comment by dtarnawsky** [comment]
Hi @timeisgolden , Can you confirm you have npm installed?
You can test this by running this at the command line:
`/usr/local/bin/npx -v`

It should return a version number.
If you don't have npm installed it will be installed when you run the installer from [nodejs.dev](https://nodejs.dev/)

**Comment by dtarnawsky** [comment]
Hey @timeisgolden , another user found that if you have your $PATH set to .bashrc then you may need to run the following to get npm to run in zsh:
`npm config set script-shell /bin/zsh`

Try it out and let me know.

**Comment by timeisgolden** [comment]
> 

Hi, Thanks for your reply, 
yeah, it returned a version number from the path on terminal.
<img width="541" alt="image" src="https://user-images.githubusercontent.com/54345950/160135069-c9a7e641-dcdd-4ca8-b001-3875d026c71a.png">

**Comment by timeisgolden** [comment]
> 



> Hey @timeisgolden , another user found that if you have your $PATH set to .bashrc then you may need to run the following to get npm to run in zsh: `npm config set script-shell /bin/zsh`
> 
> Try it out and let me know.


yeah, I tried this, but got same issue.

**Comment by dtarnawsky** [comment]
Hey @timeisgolden, v1.4.4 is out now and it adds an option to set your shell in Settings. You can choose /bin/zsh and this should switch from /bin/sh which is the default to zsh. Hopefully, this fixes your issue.

**Comment by timeisgolden** [comment]
@dtarnawsky Thanks so much.
I will try again.
