### ISSUE TITLE
Doesn't work if ionic app is in a sub-folder

### ISSUE THREAD

**Issue by sachingargtech** [ionic-team/vscode-extension#22]
Most of our repos have /server, /scripts, /app etc folders with ionic app inside the /app folder. Currently extension only offers to create a new project.

Instead of only supporting specific monorepo setups, it might be better to add a workspace level configuration option to specify path of ionic app in the vscode workspace folder.

**Comment by dtarnawsky** [comment]
Hey @sachingarg05 , where do you keep your `package.json`? in the root folder or the `/app` folder?

**Comment by sachingargtech** [comment]
Yes, ionic's package.json is usually in /app folder.

But overall there are multiple package.json files. Inside /server and also in /app folder, or there might be multiple ionic projects in /user-app and /admin-app, etc...

**Comment by dtarnawsky** [comment]
Ok, I think that it's possible to detect this. Sort of a mono-repo but each folder is individual and nothing shared. I'll add it to the feature list. In the meantime you would need to open the folder that contains your app.

**Comment by dtarnawsky** [comment]
@sachingarg05, folder based mono repos are now supported in 1.4.1. It works by searching at least one subfolder down for Ionic based projects. Grab the latest version of the extension and try it out. Any issues or suggestions please open another issue. For now, I'm closing out this one.
