### ISSUE TITLE
There is no way to stop a running daemon(Run On Web)

### ISSUE THREAD

**Issue by timeisgolden** [ionic-team/vscode-extension#23]
After 'Run On Web' tapped, it launched at http://localhost:8100.
but there is no button to stop the running.
Furthermore, I closed the editor(vscode), but it was launching at http://localhost:8100, It's saying that it's running in the thread.
is it a missing feature?

**Comment by dtarnawsky** [comment]
Hi @timeisgolden , you can click on the task in the bottom toolbar and click Cancel. However, its been noted that people don't notice this, so a new feature has been added which you can get in the Pre-Release version which adds a "Stop" button to help make it more obvious how to shut down the development web server (or if you are running tests in watch mode).

So, grab the pre-release version now, or wait a couple of days for the final release to be sent out.

**Comment by timeisgolden** [comment]
Thanks, @dtarnawsky

**Comment by dtarnawsky** [comment]
@timeisgolden, v1.4.1 is now released and has more obvious support for stopping the "run on web" option (a nice "stop" button you can click). I'll close out this issue.
