### ISSUE TITLE
Support for workspaces

### ISSUE THREAD

**Issue by adeprez** [ionic-team/vscode-extension#24]
Thank you for the extension. I use VSCode workspace for my Ionic (and others) projects. The Ionic extension works well but it process only the first project in the list.

It would be great if there was a setting to define which project to use, or, even better, detect each Ionic project in the directory and make them roots of the Ionic UI extension tree.

> My awesome Ionic project 1
   >> Capacitor
   >> Scripts
   >> ...

> My other Ionic project 2
   >> Capacitor
   >> Scripts
   >> ...

**Comment by dtarnawsky** [comment]
Hi @adeprez, adding this feature right now. It will detect subfolders and should allow selection if they contain an Ionic Angular, React or Vue project.

**Comment by dtarnawsky** [comment]
@adeprez, folder based monorepos are now supported in 1.4.1. It works by searching at least one subfolder down for Ionic based projects. Grab the latest version of the extension and try it out. Any issues or suggestions please open another issue. For now I'm closing out this one.
