### ISSUE TITLE
Project Missing "Capacitor" Section

### ISSUE THREAD

**Issue by Rainshard** [ionic-team/vscode-extension#25]
Attached are screenshots of a new project with a "Capacitor" section and our existing project without the "Capacitor" section.
We have a "Capacitor Migration" section but it doesn't have an "Add Capacitor Migration" choice.
We already use Capacitor (maybe that's why?) but it'd be nice to have the "Capacitor" section with "Run On Android" and "Run On iOS".

![new Proj](https://user-images.githubusercontent.com/16226071/160162416-28f8e07d-c8b7-4afb-b785-ffd5e6959b54.jpg)
![owers](https://user-images.githubusercontent.com/16226071/160162437-c7e4b277-6420-44a0-84fe-628a5b252de5.jpg)

**Comment by dtarnawsky** [comment]
Hi @Rainshard , when you run the "**Remove Cordova**" option the additional features for Capacitor will appear. The extension doesn't handle scenarios where your project looks like it is both Capacitor and Cordova based.
