### ISSUE TITLE
Is it a bad idea to support Webstorm / IntelliJ?

### ISSUE THREAD

**Issue by markeames** [ionic-team/vscode-extension#26]
VS code is popular, but I personally prefer Webstorm and given it continues to do well presumably others do too. I build all mobile apps with ionic so it would nice to see if the plugin for Webstorm could be made available

**Comment by dtarnawsky** [comment]
Hey @markeames, it's not a bad idea to support Webstorm but the development of this extension has taken a lot of time. Before considering Webstorm I'll like to see how much support there is for it. Let's get people clicking the thumbs-up emoji to see how many people want this.

For now though you can always fire up the VS code IDE to clean up your project before switching back over to Webstorm.
