### ISSUE TITLE
Only Option For New Projects

### ISSUE THREAD

**Issue by redders166** [ionic-team/vscode-extension#28]
On installing the extension, in my workspace where I have one Ionic/Angular project. I can only see the 3 options for 'New Angular/React/Vue Project' none of the other advertised options.

Steps I have taken to try to resolve.

- Disable/re-enable in the workspace
- Uninstall and reinstall
- VSCode restart
- Machine restart

Any help would be much appreciated, the tool looks incredible and I need it in my life! Thanks in advance

**Comment by dtarnawsky** [comment]
Hi @redders166, if you open the folder that contains your Ionic/Angular project does it work?

The extension will show the options for a new project if the folder doesn't contain a package.json, and doesn't contain a subfolder with a package.json.

If your Ionic/Angular project is multiple subfolders away from the root folder then it won't see your project.

**Comment by redders166** [comment]
Thanks for the reply, I can confirm this works if I close the workspace and open the folder directly. Not Ideal but understandable and can be worked around, support for workspaces in a future update would be welcomed. Thanks again!

**Comment by dtarnawsky** [comment]
Hey @redders166 , are you able to describe your folder structure from the root folder?

The extension supports a few different styles of mono-repos (npm workspaces, NX, folders) and we could extend it to support more.

**Comment by redders166** [comment]
Thanks @dtarnawsky , its pretty standard. I have VSCode setup with a workspace that has 7 repos added, one of those is "BoxMate Ionic" and in there in the root is a package.json then the usual ionic.config.json, src, www etc.

**Comment by dtarnawsky** [comment]
@redders166, what does the folder structure look like? Something like this?:
Root Folder
+--- BoxMate Ionic

Or is the "BoxMate Ionic" folder in a deeper subfolder from the root?

**Comment by redders166** [comment]
@dtarnawsky folder configuration is as below:

- Codebase
- - Other Repo Name
- - Other Repo Name
- - Other Repo Name
- - BoxMate Ionic
- - - www
- - - package.json
- - - ionic.config.json

Then the VSCode setup is a workspace with BoxMate Ionic and the other Repos manually added to the workspace too. The workspace is **not** everything that is in the Codebase folder. Codebase is not actually seen by VSCode as far as I'm aware it's just here to show you where they all live and the directory steps.

**Comment by dtarnawsky** [comment]
Hi @redders166 , can you check your extension is on version 1.4.1 or higher? 

v1.4.1 introduces folder based mono repos like what you described and should work in your scenario. If you are on 1.4.1 and still having problems and can share your project then I can take a look at why it isn't working for you.

**Comment by redders166** [comment]
@dtarnawsky yes I am on 1.4.1 (Updated 2 days ago), im afraid however that sharing the project isn't really an option due to permission. If you could let me know anything else to check in the project however I can do that, really appreciate the help

**Comment by dtarnawsky** [comment]
Hey @redders166, If you can share an approximation of your project folder structure. Just replace your app with a starter app for Ionic. It should still cause the same problem. The folder structure is the more important part of reproducing the issue.

**Comment by dtarnawsky** [comment]
Closing out this issue. Any problem with this style of monorepo just needs a sample set of folders and package.json files for reproduction.
