### ISSUE TITLE
Editing Window Losing Focus When Running Application

### ISSUE THREAD

**Issue by aaronksaunders** [ionic-team/vscode-extension#29]
When I use the Run On Web Command in the side navigation panel, the terminal window that up gets updated as the application is recompiled.

If I am typing when the terminal is getting updated, the editor window is losing focus and it makes it impossible to run the app in "watch" mode and work.

I just retested the issue on the latest release

**Comment by dtarnawsky** [comment]
Hey @aaronksaunders, I'll get this fixed in the next release (should be ready in a day or two).

**Comment by dtarnawsky** [comment]
Hey @aaronksaunders , this issue should now be fixed in the v1.4.4 release. If you already have the Output window in view it will not change the focus, so you can edit your code in peace, save and see the change in the app without having to refocus on the code.
