### ISSUE TITLE
Integrate with @capacitor/configure and project

### ISSUE THREAD

**Issue by joshuamorony** [ionic-team/vscode-extension#3]
This tool looks incredible, great work!

I've only just begun playing with it, but something that strikes me right away is that it would be amazing to have this integrated with the new configure tool - I think Max mentioned he wasn't sure on the best approach to actually executing the configure scripts, perhaps it would be cool to just have buttons under the Capacitor heading to run or edit the configuration.

**Comment by dtarnawsky** [comment]
Hey Josh,

That's definitely a doable feature. Having Capacitor Configuration visually editable would be great (with [@capacitor-configure](https://github.com/ionic-team/capacitor-configure)). 

A User Interface for:

- iOS and Android bundle ids
- Version and build number
- Display name
- Configurations such as Face ID Usage Description etc
- Icon and Splash Screen

**Comment by dtarnawsky** [comment]
0.0.0.5 is now released and includes options to display and edit the display name of the app, bundle id, version number and build number.
