### ISSUE TITLE
Sidebar changes to Ionic's panel without user interaction

### ISSUE THREAD

**Issue by FrozenKoi** [ionic-team/vscode-extension#31]
Sometimes the sidepanel changes to the Ionic pane without user interaction. 

For example I could have the Search pane open and be typing in an editor, when suddenly the Search pane switches to the Ionic pane and steals focus. So what I'm typing is now entered into the Ionic panel instead of the code editor.

I haven't been able to determine what exactly triggers this. At first I thought I was pressing a key shortcut by mistake, but it has also happened while I'm not doing anything but staring at VS Code.

As possible clues:
- I am not signed in to the extension, (it may be due to trying to sign up but not completing the sign-up or login process in the browser that opens up)
- I am running an app and VS Code is debugging it

VS Code version:
Version: 1.66.0 (user setup)
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:14.623Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19042

Ionic extension version 1.4.4

**Comment by dtarnawsky** [comment]
Hi @FrozenKoi , when debugging for the web the side panel will switch to the debug view. When you finish debugging your app it will return back to the Ionic side panel. I think this is what you are noticing: it is the only place in the extension where it will switch the side panel view.

**Comment by FrozenKoi** [comment]
Then maybe it's some other interaction that is causing this. I have seen it switch from a different pane in the Primary Side Bar to the Ionic pane, and also seen the Primary Side Bar switch from closed to open and in the Ionic pane.

(I tried restarting VS Code and not doing a failed sign/login; still seeing that switch to Ionic).

For example if I'm in this state (sorry that I'm not showing more content, company private data etc. etc.)
![image](https://user-images.githubusercontent.com/5397376/161775528-ec2b9023-ab2c-4d8f-b2a9-ddad1e070a41.png)
at some point will be switched to this state
![image](https://user-images.githubusercontent.com/5397376/161775662-d6d9b6c7-c8d6-4abd-b8c3-a77730ed1527.png)

What other information can I share that would be useful in replicating or debugging this?

**Comment by cuni0716** [comment]
Also the ionic output always returns to foreground after each save file

**Comment by dtarnawsky** [comment]
Hi @cuni0716 and @FrozenKoi ,

1.6.2 is now out and this should be fixed. Focus will only ever happen once on the first action triggered by the Ionic Extension.
