### ISSUE TITLE
Error when trying to initialize a new ionic project

### ISSUE THREAD

**Issue by scorpion81** [ionic-team/vscode-extension#32]
Just creating a new folder, activating this extension (ionic 6 cli is installed) makes a little popup with an error message appear in the bottom right corner. /bin/sh Line 1: ionic not found. Seems in one of the scripts of this extension ionic is not found ?!
Running ionic in the integrated terminal of VS Code (bash) works perfectly fine.

I am using VS Code 1.66 under Manjaro linux, both release and preview versions of the extensions dont work.
And why is there no source code available for that extension ? 

![Bildschirmfoto von 2022-04-09 16-54-13](https://user-images.githubusercontent.com/1172149/162581656-fb2a2f1a-973f-4846-9a3e-eed64a765799.png)

**Comment by dtarnawsky** [comment]
hi @scorpion81 ,

We've just fixed this issue in version 1.5.2 released today. The reason for this is that you don't have @ionic/cli installed globally with npm, however in 1.5.2 you no longer need to, it will use a internal copy of @ionic/cli unless you have one installed locally. Please try out 1.5.2 and let me know if you have any issues.

**Comment by scorpion81** [comment]
hi @dtarnawsky, thank you for the quick response and the fix :) 
But unfortunately another error happens now. "Cannot read properties of undefined, reading @ionic/cli"
![Bildschirmfoto von 2022-04-09 20-23-54](https://user-images.githubusercontent.com/1172149/162586996-19459fe2-b4cb-4678-bbec-bb27f395439d.png)
I additionally entered afterwards "which ionic" into vs code's terminal in order to show that i have installed node and ionic via nvm. Is that maybe a problem ? Because node is kinda "locally" installed but not really, it looks for ionic as it was globally. And ionic is apparently installed the same way.

**Comment by dtarnawsky** [comment]
Hey @scorpion81, 1.5.3 should fix that error (was testing with cached data and missed that). Hopefully, this fixes the problem for you.

**Comment by scorpion81** [comment]
Hey @dtarnawsky thanks again :) Now it is working perfectly for me.
