### ISSUE TITLE
Tips for setting ANDROID_SDK_ROOT?

### ISSUE THREAD

**Issue by mlynch** [ionic-team/vscode-extension#33]
I tried to run my app on Android and ran into the issue below (extension version: 1.5.2):

<img width="1904" alt="image" src="https://user-images.githubusercontent.com/11214/162592739-820a5b99-4a89-488e-aa4c-9f933b3fae11.png">

I often have to set this value locally, but perhaps a way to provide or auto-detect this value in the extension could be helpful? Also if I set this environment variable in the terminal in VS Code it doesn't seem to effect the environment for commands run from the extension

**Comment by dtarnawsky** [comment]
Interesting, when a task a run (using child_process.exec) it inherits all environment variables (process.env) and these should include everything that was set by your shell. As I use zsh these come from the .zshenv and my file includes the usual things you would need to get your terminal building Android stuff:
```
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_291.jdk/Contents/Home
export GRADLE_HOME=/usr/local/opt/gradle/libexec
export ANDROID_HOME=~/Library/Android/sdk
export PATH=${PATH}:${ANDROID_HOME}/tools
export PATH=${PATH}:${ANDROID_HOME}/platform-tools
```
The extension allows you to set your shell in settings and I wonder if you were to set the shell to either /bin/zsh or /bin/sh whether it would pick up your environment variables and work.

**Comment by dtarnawsky** [comment]
In the 1.5.5 pre-release if you do not have ANDROID_HOME set then the extension will select a default for you, similarly with the Android Debug Bridge (which is required for debugging Android Web Views).

**Comment by dtarnawsky** [comment]
With 1.5.8 now out if you do not have ANDROID_HOME set then the extension will select a default for you, similarly with the Android Debug Bridge (which is required for debugging Android Web Views). I'll close out this issue for now.
