### ISSUE TITLE
[Critical bug] Extension doesnt start if VSCode is installed in other drivers [D,E,F,G,H ... Z]

### ISSUE THREAD

**Issue by mary-ng5519** [ionic-team/vscode-extension#34]
Folks, we love your work, please help investigate below logs and fix the bug asap
```
Microsoft Windows [Version 10.0.19042.1586]
(c) Microsoft Corporation. All rights reserved.

D:\Demos\ionic6-starter-app>which code
/cygdrive/d/Program Files/Microsoft VS Code/bin/code
```
```
'c:\Users\phineas\.vscode\extensions\ionic.ionic-1.5.7\node_modules\@ionic\cli\bin\ionic' is not recognized as an internal or external command,
operable program or batch file.
```

![image](https://user-images.githubusercontent.com/59623591/162643361-5d9e3ea3-8f34-4c79-9826-6208658bb67e.png)

**Comment by dtarnawsky** [comment]
Thanks for the bug report Paul @phathuynh5519, this issue should now be fixed in 1.5.8 released this morning. Be sure to update and then restart VS Code.
