### ISSUE TITLE
Support for multiple targets (iOS)

### ISSUE THREAD

**Issue by jansgescheit** [ionic-team/vscode-extension#35]
For testing of new features we build on our Ionic / Capacitor App on a Staging Target and push theses to an other appId to Apple Test Flight.

In this Extension i can only choose one appId, in my case it's our staging appId. I don't know how i can change it. In our `capacitor.config.ts` the `ios.scheme` is set to our production scheme.

**Comment by dtarnawsky** [comment]
Hi @jansgescheit, do you have a sample project you could share? It can be sent to damian@ionic.io

**Comment by dtarnawsky** [comment]
The -`-flavor` and -`-scheme` arguments have been added to a recent version of the Capacitor CLI. There is an issue with the Ionic CLI passing these to the Capacitor CLI and when this is fixed them the feature can be added to the extension.
