### ISSUE TITLE
yarn support

### ISSUE THREAD

**Issue by danielehrhardt** [ionic-team/vscode-extension#36]
Could you add yarn support?
Maybe selection or if there is no package-lock.json and a yarn.lock use yarn.

**Comment by dtarnawsky** [comment]
Hi @danielehrhardt ,

Yarn support is ready to go! You can get it in the v1.5.9 pre-release. If you go to your extensions tab, choose Ionic and click the down arrow next to install you can choose to install the pre-release.
![Screen Shot 2022-04-13 at 1 27 11 PM](https://user-images.githubusercontent.com/84595830/163266560-2b72cfe4-fc20-424b-a98d-e37bd5527e7a.png)

Give it a go. v1.5.9 is likely to be released at the end of the week.
