### ISSUE TITLE
Dont nag for login or account creation in the sidebar or at least dont auto activate/focus the sidebar view continiously

### ISSUE THREAD

**Issue by stefanrybacki** [ionic-team/vscode-extension#37]

**Comment by dtarnawsky** [comment]
Hi @stefanrybacki,

If you login you'll stay logged and will never be nagged again. Any reason you do not want to login with an Ionic Account?

**Comment by stefanrybacki** [comment]
No reason, I just installed the extension for later evaluation and it keeps stealing focus of active sidebars, so I had to disable the extension. I'd rather nit disable it but not having it constantly stealing focus.

**Comment by dtarnawsky** [comment]
Hi @stefanrybacki,

v1.6.2 is out and this resolves the activate/focus problem. The extension will only ever focus once when it is activated when VS Code starts up.
