### ISSUE TITLE
Stop debug doesn't stop server

### ISSUE THREAD

**Issue by matteobortolazzo** [ionic-team/vscode-extension#38]
Hi, I am using the latest version (1.5.13).

When I stop a debug session, the server keeps running until I close VS Code.
So if I press Debug on the web again, it starts on a new port, causing issues with CORS.

Is there a way to manually stop it?

Thanks

**Comment by dtarnawsky** [comment]
Hi @matteobortolazzo , would you happen to be using [Volta](https://volta.sh/)?

**Comment by matteobortolazzo** [comment]
Hi, no just a new react ionic project that is running on WSL

**Comment by dtarnawsky** [comment]
Aha, on Windows specifically, I'll test it out. The extension uses node's process [kill](https://nodejs.org/api/process.html#processkillpid-signal) command so perhaps there is a problem there...

**Comment by dtarnawsky** [comment]
Hi @matteobortolazzo,

This issue should now be fixed in 1.5.14!

**Comment by matteobortolazzo** [comment]
Works like a charm, thanks @dtarnawsky !!
