### ISSUE TITLE
Hide Serving dialog

### ISSUE THREAD

**Issue by henkjurriens** [ionic-team/vscode-extension#4]
When you use 'Run on Web' the dialog Serving keeps open. Is it possble to hide it?

**Comment by dtarnawsky** [comment]
Hi Henk,

That's a great suggestion. It isn't possible at the moment but it will be in the next release (0.0.4). Hoping to have this updated and ready for monday.

**Comment by henkjurriens** [comment]
👍

**Comment by dtarnawsky** [comment]
The "Run on Web" option is now shown on the status bar in v0.0.4. Note: It can be clicked and canceled. There are a few other operations like Sync that will do this now as well.

Other features in 0.0.4:
- When running most tasks the progress dialog should be hidden
- If node_modules folder is not found then recommendation given for npm install
- Speed improvement between operations by caching npm outdated call
- If @capacitor/core is upgraded then also upgrade @capacitor/ios and @capacitor/android
- Test the minimum version of node when run
- Application name can be changed when a new project is created
- Fix for running iOS apps with live reload
- Display version numbers when selecting iOS devices
