### ISSUE TITLE
login doesn't work on extension.

### ISSUE THREAD

**Issue by coupdi** [ionic-team/vscode-extension#42]
Installed the Extension, and opened the Ionic Tab, and it presents me with the Login, Sign Up, or Skip for Now.  
I have an Ionic login already, so I clicked Login - it thinks for a brief second, but nothing obvious happens.  Same behavior with Sign Up.

I am able to skip, so low priority, not even sure what I can look forward to when I do login...  :)

No output, no terminal activity, no browser tabs.  Happy to provide more info, but not sure what you will want.

**Comment by johnbertram-github** [comment]
Same here... :-(

**Comment by dtarnawsky** [comment]
Hey @coupdi and @johnbertram-github,

You should now be able to login or signup in the 1.7.7 release. Thanks for the bug report. The login option is designed to give some great new features we're planning around use of App Flow and other Ionic services.

**Comment by johnbertram-github** [comment]
@dtarnawsky Thank you so much! Updated and away I go. The GUI is definitely something I will find useful. Thanks again for jumping on it and being so accessible!

**Comment by coupdi** [comment]
> @dtarnawsky Thank you so much! Updated and away I go. The GUI is definitely something I will find useful. Thanks again for jumping on it and being so accessible!

that.
