### ISSUE TITLE
Re-build the app when Run web/Android or Hot-reload with new changes

### ISSUE THREAD

**Issue by uniquedj95** [ionic-team/vscode-extension#43]
When running the application on either web or android, The extension is loading the built app, forcing one to go back to the terminal to build the app before the extension's run command.

I think the best experience could be silently running the build command first whenever one runs the application using the extension. This will help to take into account any changes made to the application.

It will also be great to hot-reload/rebuild the application whenever new changes are made without manually restarting the application

**Comment by dtarnawsky** [comment]
When you run in Web, Android and iOS it will always build the application prior to running it. 

The option to live-reload your app can be found in Settings -> Live Reload.

If you ever make a change in your IDE and save a file, the extension will also build prior to run when live reload is off.

Finally, the build command can be found under "Capacitor" so you shouldn't have to go to the command line to build.

If you have found a scenario where you have found a set of steps that cause a bug I'd be happy to help. I may need a sample project through.
