### ISSUE TITLE
Error Viewing Splash Screen & Icons

### ISSUE THREAD

**Issue by rgilsimoes** [ionic-team/vscode-extension#44]
In the Splash Screen & Icons separator selecting the "View" opens an editor with the following error:

![image](https://user-images.githubusercontent.com/20357414/170559037-1d348159-e22f-437b-be8c-a46b62ba36b4.png)

**Comment by Husnain-Aleem** [comment]
I have installed the official Ionic extension for VS Code today. But "Splash Screen & Icon" and "Configuration" options are not available in it.

![Screenshot 2022-05-29 093400](https://user-images.githubusercontent.com/80635252/170852413-e415379a-2bcc-4009-b8d3-09895ba1536c.png)

**Comment by Husnain-Aleem** [comment]
I have installed the official Ionic extension for VS Code today. But "Splash Screen & Icon" and "Configuration" options are not available in it.

![Screenshot 2022-05-29 093400](https://user-images.githubusercontent.com/80635252/170852481-71ec5ea1-d9f9-49bb-8b6f-ec511831451c.png)

**Comment by dtarnawsky** [comment]
> I have installed the official Ionic extension for VS Code today. But "Splash Screen & Icon" and "Configuration" options are not available in it.

hi @Husnain-Aleem, your project is a Cordova based. You'll need to migrate it to Capacitor before you can unlock features like Splash Screen / Icon asset generation as well as debugging etc.

**Comment by dtarnawsky** [comment]
> In the Splash Screen & Icons separator selecting the "View" opens an editor with the following error:

HI @rgilsimoes,

Thanks for the bug report Ricardo! Looks like the problem was isolated to just Windows computers. I've fixed the issue in 1.8.3 which VS Code should automatically update to. You can also check the version number in the extensions area.

**Comment by rgilsimoes** [comment]
I can confirm the issue is gone! Thank you @dtarnawsky
