### ISSUE TITLE
Feature Request: Ability to define skipFiles

### ISSUE THREAD

**Issue by KGHawes-DeLess** [ionic-team/vscode-extension#45]
...for debugger, or a configuration instruction if this is already possible. Thanks!

**Comment by dtarnawsky** [comment]
Thanks for the feature request @KGHawes-DeLess!

I've added this option to v1.8.4. If you go to Settings -> Advanced you'll see an option for "Debug Skip Files" where you can specify an array of glob patterns that will be used when debugging in Web or Android. An example value might be `["!**/node_modules/**","<node_internals>/**"]`

Let me know if this works well for your scenario!

**Comment by KGHawes-DeLess** [comment]
Excellent...I didn't expect such a rapid response. Very much appreciated, thank you!!
