### ISSUE TITLE
Option to set `--public-host`

### ISSUE THREAD

**Issue by martinmitteregger** [ionic-team/vscode-extension#49]
Currently when running the application on a device it fails because multiple network interfaces are detected. (**Ionic Extension v1.8.5**)

```
[[40mERROR[49m] Multiple network interfaces detected!
        
        You must select an external-facing IP for the dev server that your device or emulator can access with the --public-host option.
[Ionic] npx ionic cap run android -l --external --target=xxxxxxxxxx Failed
[Ionic] Android Completed.
```

When running the above mentioned command manually I have to select which IP i want to use which could be bypassed by using the `--public-host` option.

```
[WARN] Multiple network interfaces detected!

       You will be prompted to select an external-facing IP for the dev server that your device or emulator can access.
       Make sure your device is on the same Wi-Fi network as your computer. Learn more about Live Reload in the docs[1].

       To bypass this prompt, use the --public-host option (e.g. --public-host=172.27.240.1). You can alternatively bind
       the dev server to a specific IP (e.g. --host=172.27.240.1).

       [1]: https://ion.link/livereload-docs

? Please select which IP to use: (Use arrow keys)
> 172.27.240.1 (vEthernet (Default Switch))
  172.25.240.1 (vEthernet (Wi-Fi))
  172.31.224.1 (vEthernet (WSL))
  192.168.178.46 (Wi-Fi)
  172.29.192.1 (vEthernet (Ethernet))
```

I would appreciate an option where we can set the IP which should be used when running the command directly from the extension.

**Comment by dtarnawsky** [comment]
Thanks for the bug report @martinmitteregger, this problem has been fixed in 1.8.6. Now, if you have both "Live Reload" and "External IP Address" turned on and have multiple network interfaces you will be asked which one to use prior to running for web/ios/android.

Let me know if this fixes your issue!
