### ISSUE TITLE
Modify Version and Build?

### ISSUE THREAD

**Issue by lunedam-git** [ionic-team/vscode-extension#51]
I used to be able to modify the version number and build number of the Android and IOS projects within an Ionic Capacitor project using this extension in the 'Configuration' section like in [this example](https://user-images.githubusercontent.com/84595830/159510925-6b989ac4-0ce9-445e-a578-b83b5c4be38f.gif).

This 'Configuration' section is no longer present. Any idea how I get it back? That was a really handy time saver.

**Comment by dtarnawsky** [comment]
Hi @lunedam-git,

The Configuration section will appear if you Capacitor in your project, it detects this by looking for `@capacitor/core` in your `package.json` file. In mono-repos this may be the `package.json` containing `@capacitor/ios` or `@capacitor/android`.

If you can attach a copy of your `package.json` I'd be happy to take a look to see why it isn't adding the Configuration section.

**Comment by lunedam-git** [comment]
Hey @dtarnawsky ,

Thanks for getting back to me. I have `@capcitor/core` in my package.json, as well as both `@capacitor/ios` and `@capacitor/android`.

It is now showing up again so all seems well. Started appearing again after I'd removed my ios folder and then added it again with `npx add ios` following some strange pod issues after updating Xcode. Can only assume that something had gone amiss in there and was preventing the configuration option from appearing in the plugin. Got no errors or anything like that though, which was what was puzzling me.

**Comment by dtarnawsky** [comment]
Hey @lunedam-git, I think you must have bumped into an odd scenario, where the ios folder was deleted when the extension was launched, and then needed to be refreshed when you ran `npx add ios`. If you run into anything like this then try out the refresh button on the top right corner of the side panel.

**Comment by lunedam-git** [comment]
No. The IOS folder and contents was there when the config option was absent. It was later when I went to run my (Ionic) project that I found the glitch with the pods and removed then re-added IOS. 

Not to worry though. Seems to be happy enough agin now.
