### ISSUE TITLE
npm and npx are not found

### ISSUE THREAD

**Issue by amrography** [ionic-team/vscode-extension#54]
![Screen Shot 2022-08-31 at 9 25 36 AM](https://user-images.githubusercontent.com/9614340/187618600-598298c7-2ef8-4a3f-8122-86b65524e167.png)

npx command isn't found when trying to run the web version. and npm not found when I am trying to run build script. I have node only via **nvm**. Is this should be the cause of the problem ? I can run all commands in normal terminal with no issues

**Comment by dtarnawsky** [comment]
You may need to go to `Settings` -> `Advanced` and specify your Shell Path. eg `/bin/zsh`.

**Comment by amrography** [comment]
@dtarnawsky My path is correct and I can run npx on zsh with no issue

**Comment by dtarnawsky** [comment]
If you install Node on your machine then VS code extensions like Ionic can use Node to execute commands.

**Comment by dtarnawsky** [comment]
Just had the same issue appear after updating to the latest 12.6 MacOs Monterey. It was resolved by restarting the mac.
