### ISSUE TITLE
Capacitor 4 migration doesn't show in recommendations

### ISSUE THREAD

**Issue by arielhasidim** [ionic-team/vscode-extension#55]
I use Capacitor version 3.x.x. and I want to upgrade to 4.x.x.

According to the [official announcement ](https://ionicframework.com/blog/announcing-capacitor-4-0/) I can use _"[Ionic Extension](https://ionic.link/vscode) for a 1-click migration"_, but the extension's recommendations dropdown doesn't show this option. 

Furthermore, when I try to run manually `npm i -D @capacitor/cli@latest` and then `npx cap migrate`, I get this message: _"Please note this tool is not intended for use in a mono-repo enviroment, please check out the Ionic vscode extension for this functionality."_

See the screenshot:
<img width="1209" alt="Screen Shot 2022-09-02 at 13 48 18" src="https://user-images.githubusercontent.com/23483971/188124797-663c3de9-cb42-4aff-a46c-1a32a9899258.png">

**Comment by dtarnawsky** [comment]
If this is a project you can share then please send a zipped copy (or link to one) to support@ionic.io and mention Damian in the title of the email. I can take a look at the project and identify the issue quickly. 

Based on the message in the CLI you are probably not using npm (maybe pnpm, yarn?) or are using npm workspaces. Without some details of the project structure it isn't clear why npm outdated might not be reporting the version of @Capacitor/Core (which is what the extension relies on to suggest migrating to Capacitor 4).

**Comment by arielhasidim** [comment]
Thank you.
I am using npm, but I did not understand correctly that I should update Capacitor core to 4.0 before being able to migrate through VSC.

I think it's not clear enough as I understood that the "OR" is between the first two paragraphs and the next one:

<img width="741" alt="Screen Shot 2022-09-10 at 16 43 22" src="https://user-images.githubusercontent.com/23483971/189486314-81907e0e-7599-4b42-a52b-c9251d2c5648.png">
