### ISSUE TITLE
Keyboard Shortcut for "Run Android"

### ISSUE THREAD

**Issue by therhenals** [ionic-team/vscode-extension#57]
You could implement this feature to be able to run the app from a keyboard shortcut.

**Comment by dtarnawsky** [comment]
Hi @therhenals,

Thanks for the suggestion! 

We've added a feature in the v1.10.0 release which allows you to run the app by pressing cmd+R (or Ctrl+R on Windows). 

This will run the last platform you previously ran or will run for Web by default. 

As extensions need to be activated before keyboard shortcuts work you'll need to have clicked the Ionic icon at least once in a VS Code session to allow cmd+R to work.
