### ISSUE TITLE
Question: run Ionic CLI commands with `npx`

### ISSUE THREAD

**Issue by robingenz** [ionic-team/vscode-extension#6]
Hey,
I noticed the following:
Capacitor CLI commands are executed with `npx` (e.g. `npx cap open android`).
Ionic CLI commands are executed without `npx` (e.g.: `ionic cap run ios -l --external`).

Is there a reason for this?

I would like both to be executed with `npx`.

**Comment by dtarnawsky** [comment]
The extension has a dependency on the Ionic cli being installed globally and with that installed can run the `cap` commands via `npx`. I've got a task to have the extension switch to either using Ionic cli only or cap cli only based on the project so once that is done each command will be run the same way.

**Comment by robingenz** [comment]
The reason why I would like to run the Ionic CLI also with npx is that we have always installed the Ionic CLI in our projects as a dev dependency (e.g. https://github.com/robingenz/capacitor-plugin-demo/blob/4261e4f9e1dec7a852a9a286163cf1e24cbdd0d1/package.json#L64). So we make sure that everyone in the team uses the same CLI version.
If I remember correctly, `npx` looks first in the local project folder for the package and then globally.
So it would fall back to the global installed version.

But this is, of course, only a small detail. I am curious about the coming changes. Please feel free to close the issue.

**Comment by dtarnawsky** [comment]
@robingenz [Version 0.0.10](https://vs-ionic.netlify.app/) addresses this issue. All calls are made with npx so that if the ionic or capacitor cli are installed locally they will be called first.

There are plenty of other [features in 0.0.10](https://github.com/ionic-team/vscode-extension/wiki#version-0010)

**Comment by robingenz** [comment]
Thank you so much @dtarnawsky! 🎉
