### ISSUE TITLE
Doesn't works since 1.10.0

### ISSUE THREAD

**Issue by Borongaj** [ionic-team/vscode-extension#60]
No more commands respond from the panel.

I've checked with all new updates (1.10.1, 1.10.2 and 1.10.3).

Everything is working with 1.9.9.

**Comment by dtarnawsky** [comment]
Can you update your @ionic/cli? 
`npm install @ionic/cli --save-dev`
 
There was an issue with v6.20.1 that cause commands to be ignored which was just fixed in v6.20.3

**Comment by Borongaj** [comment]
All seems working again.

Thank you!
