### ISSUE TITLE
Capacitor not recognized in an existing project

### ISSUE THREAD

**Issue by adamrz** [ionic-team/vscode-extension#61]
I recently installed v1.9.9 of the plugin to vscode. However I can't seem to get it to recognize that Capacitor is already added as an integration. I've clicked "Add Capacitor Integration" but e result is that it's already added. Any suggestions?

![image](https://user-images.githubusercontent.com/1616718/194442982-60f33a19-7a24-41fd-bde3-6e75603f6fe4.png)

**Comment by dtarnawsky** [comment]
Can you check in your package.json to see if there is a leftover `cordova` section, if you remove that it will show up like a Capacitor project.

**Comment by dtarnawsky** [comment]
A new feature was added in 1.13.0 that detects if your Capacitor project has Cordova settings in your `package.json` and will fix by removing them.

I'll close out this issue as it is likely resolved by this new feature.
