### ISSUE TITLE
The Ionic side bar keeps stealing the focus

### ISSUE THREAD

**Issue by evlist** [ionic-team/vscode-extension#62]
Hi,
I have installed version v1.10.6 and the Ionic side bar keeps stealing the focus.
This might be because I have a few warnings:
![image](https://user-images.githubusercontent.com/109022/196699912-4cd2f9c0-13e1-4ceb-ad95-98181764b9c5.png)
But these are not my priority right now and this sidebar that keeps stealing the focus and hiding the file browser when need it is really too much ! 
Is there another way to keep it hidden than uninstalling the extension ?
Thanks,
Eric

**Comment by dtarnawsky** [comment]
Hi Eric,

I was wondering if you were pressing cmd/ctrl + R on the keyboard when using the file browser? or was there another trigger that you were doing when it switched focus to the Ionic extension?

**Comment by evlist** [comment]
Hi Damian,
Trying to understand when that's happening I must admin I might have been exaggerating when I said "keeps stealing": I am debugging my app with a Javascript debug terminal in which I am running "npm test" and the ionic sidebar get the focus after each run.
I am having a hard time with this app, I am doing a lot of debugging and I had the feeling that the sidebar was continuously "stealing the focus" but it seems that it's only in that case!

**Comment by dtarnawsky** [comment]
I believe this is caused by running the test in the extension first, then trying it in the terminal - the extension will report errors in your tests until you fix them all.

If there is a good way to reproduce this issue I'll reopen and fix.
