### ISSUE TITLE
capacitor 4 upgrade duplicates exported=true if already exists

### ISSUE THREAD

**Issue by jcesarmobile** [ionic-team/vscode-extension#63]
App that already has the `android:exported="true"` https://github.com/jcesarmobile/capacitor-migration-issue/blob/main/android/app/src/main/AndroidManifest.xml#L19

After migration it includes two `android:exported="true"`
https://github.com/jcesarmobile/capacitor-migration-issue/blob/vs-migration/android/app/src/main/AndroidManifest.xml#L13-L18

**Comment by dtarnawsky** [comment]
Resolved in 1.11.0.
