### ISSUE TITLE
capacitor 4 migration downgrades gradle

### ISSUE THREAD

**Issue by jcesarmobile** [ionic-team/vscode-extension#64]
If the app is already using a newer version of gradle plugin than 7.2.1 (i.e 7.3.0), the migrator downgrades to 7.2.1
https://github.com/jcesarmobile/capacitor-migration-issue/pull/1/files#diff-197b190e4a3512994d2cebed8aff5479ff88e136b8cc7a4b148ec9c3945bd65aL10

**Comment by dtarnawsky** [comment]
Resolved in 1.11.0.
