### ISSUE TITLE
capacitor 4 migrator adds unused variables

### ISSUE THREAD

**Issue by jcesarmobile** [ionic-team/vscode-extension#65]
It adds some variables that some plugins might need, should only update them if they exist, but not add them if they don't exist

https://github.com/jcesarmobile/capacitor-migration-issue/pull/1/files#diff-3b465cff0489a1e881341d0657f2fc4beb5ac547c2496908a50b6024ec13ce49R16-R20

**Comment by dtarnawsky** [comment]
Resolved in 1.11.0.
