### ISSUE TITLE
capacitor 4 migration doesn't change registerPlugin order

### ISSUE THREAD

**Issue by jcesarmobile** [ionic-team/vscode-extension#66]
In Capacitor 4 the registerPlugin should be called before super.onCreate. `npx cap migrate` command does it, see https://github.com/jcesarmobile/capacitor-migration-issue/pull/3/files#diff-8654f01de5718748d9cd6350903d38603a74eb1c42fcc9b037730275298ffc8dR11
but the vs extension doesn't.

**Comment by dtarnawsky** [comment]
Resolved in 1.11.0.
