### ISSUE TITLE
Feature: back button for preview

### ISSUE THREAD

**Issue by Boyownik** [ionic-team/vscode-extension#67]
Am not sure if it is already possible, but having "back"/"return" button next to "home" on preview would be nice. If it is actually possible to somehow enable it, please let me know how 😄 
![obraz](https://user-images.githubusercontent.com/27145369/197594360-b0609ee9-6606-4e7f-b635-cd2db4901bc0.png)

**Comment by dtarnawsky** [comment]
We've added a back button for the editor preview in 1.13.0!

Thanks for the suggestion @Boyownik
