### ISSUE TITLE
Problem "enoent package.json not found" in root of project

### ISSUE THREAD

**Issue by lokize** [ionic-team/vscode-extension#68]
Hi, My project hava a subfolder (like frontend) and the extension dont find package.json inside this folder, any way to make this extension to search this file and not in root path?

**Comment by dtarnawsky** [comment]
Hi @lokize,

Is the folder something that you can share?

_(That way I can reproduce the problem you are having)_

**Comment by lokize** [comment]
its a vue3 starter project but in ./frontend folder not root of project

**Comment by dtarnawsky** [comment]
Hi @lokize ,

Here's a sample vue app that is located in a folder called frontend:
[https://github.com/dtarnawsky/cs-vue-starter](https://github.com/dtarnawsky/cs-vue-starter)

This works fine with the Extension whether you open the root folder or the frontend folder.

To reproduce your issue I'd need a sample project that has the issue.

**Comment by lokize** [comment]
thanks for reply, i tried to create another project and worked fine. thank you very much!
