### ISSUE TITLE
Run command does not take into account of specific build (based on angular environment files)

### ISSUE THREAD

**Issue by Borongaj** [ionic-team/vscode-extension#69]
I can build and run for a specific platform and env from command line (but without live reload).

`ng build --configuration=staging --output-hashing=none && npx cap sync ios && npx cap run ios`

Using the extension (because I need live reload option), I can build staging (from build ellipsis menu), but if I click the run button (Web, Android or iOS), a build is made, based on default env file.

How to run from a staging env, while benefiting live reload?

Thanks.

**Comment by dtarnawsky** [comment]
Thanks for the suggestion @Borongaj ,

Version 1.12.0 was just released and will help you with this. When selecting a build type it now displays it (eg production, staging), it will also use that configuration when running for web, iOS or Android. So, when you are using live reload it will also be using the configuration you chose in the build selection (three dots).

**Comment by Borongaj** [comment]
Thank you very much @dtarnawsky !

But I still have this issue : https://github.com/ionic-team/vscode-extension/issues/59

**Comment by Borongaj** [comment]
Build (staging) : ok

Run iOS :

`[ng] An unhandled exception occurred: Configuration 'staging' is not set in the workspace.`

[Screenshot](https://drive.google.com/file/d/12PTr03nD-P183oPyNVC5FoptURk4ex8i/view?usp=sharing)

**Comment by Borongaj** [comment]
Seems that Run command still does not respect the build configuration.

**Comment by dtarnawsky** [comment]
The error: `An unhandled exception occurred: Configuration 'staging' is not set in the workspace.` indicates that your `angular.json` file is missing the configuration `staging` from the `serve` > `browserTarget` > `configurations`:
```json
"serve":{
    "configurations": {
        "staging": {
            "browserTarget": "app:build:staging"
        },
    }
 }
```

**Comment by Borongaj** [comment]
Thanks, but I already have this conf :

```
"serve": {
                    "builder": "@angular-devkit/build-angular:dev-server",
                    "options": {
                        "browserTarget": "app:build"
                    },
                    "configurations": {
                        "staging": {
                            "browserTarget": "app:build:staging"
                        },
                        "production": {
                            "browserTarget": "app:build:production"
                        },
                        "ci": {
                            "progress": false
                        }
                    }
                },
```

**Comment by dtarnawsky** [comment]
If you try out this repo it has staging, production and ci: [https://github.com/dtarnawsky/cs-toast](https://github.com/dtarnawsky/cs-toast)

After selecting `staging` from the `build` menu it runs correctly for `Web`, `iOS` and `Android`.

If this repo works on your machine then I'll need a sample repo that has the problem to help any further.

**Comment by Borongaj** [comment]
Thanks. All works fine.

**Comment by dtarnawsky** [comment]
Ok great! I'll close out the issue.

**Comment by Borongaj** [comment]
> Seems that Run command still does not respect the build configuration.

For several weeks (months), the bug reappeared. Once a type of compilation chosen by the ellipses (for example: staging) and launched, it is not memorized by the plugin. The second time, by clicking directly on "Build (staging)", the default configuration is used, and not the one displayed in parentheses.

**Comment by dtarnawsky** [comment]
Thanks @Borongaj, I've found and fixed this issue for the build command and it should be resolved in the next release.
