### ISSUE TITLE
Support VS Code Workspaces

### ISSUE THREAD

**Issue by piotr-cz** [ionic-team/vscode-extension#70]
Extension doesn't pick up existing project when:
- Project is a folder of [VS Code multi-root Workspace](https://code.visualstudio.com/docs/editor/workspaces#_multiroot-workspaces)
- Project is not first in list

In this context VS Code workspaces should not be mistaken with npm workspaces.

Example worskspace `Apps.code-workspace` file:

```json
{
  "folders": [
    {
      "path": "api",
      "name": "Api"
    },
    {
      "path": "mobile",
      "name": "Ionic App"
    }
  ]
}
```

Here only when *Ionic App* is first in list, it's picked by extension and related menu items shows up (*Run*, *Debug*, etc).
In other cases, only *New Angular Project*, *New React Project* and *New Vue Project* shows up.

References:
- [Multi-root Workspaces in Visual Studio Code](https://code.visualstudio.com/docs/editor/multi-root-workspaces)
- [Workspaces in Visual Studio Code](https://code.visualstudio.com/docs/editor/workspaces)

Related issues that were closed as resolved because of monorepo feature:
- https://github.com/ionic-team/vscode-extension/issues/24
- https://github.com/ionic-team/vscode-extension/issues/28

**Comment by dtarnawsky** [comment]
Hi @piotr-cz,

Version 1.17.0 now supports VS Code Workspaces!

Give it a try and let me know if you run into any problems.

**Comment by piotr-cz** [comment]
@dtarnawsky 
I just tested v1.17.0 and extension still doesn't work for me with setup as in issue description.

Using latest VS Code v1.74.1

**Comment by piotr-cz** [comment]
Maybe an UI such as the one which is used for VS Code *Source Control* would be better for this case?

When workspace is opened, each folder is presented as an accordion item.

**Comment by dtarnawsky** [comment]
Hi @piotr-cz,

Are you able to supply a sample (either zipped copy or github repo) that doesn't work for you?

Can you confirm that you are using 1.17.0?

**Comment by wsamoht** [comment]
I just did some testing and I cannot replicate the issue on 1.17.0 on a new VS code workspace. On an existing workspace with 8 folders/projects, 3 of the 8 are being recognized as Ionic projects when in fact only one is. I had to manually select the `****-mobile` project in the Ionic plugin Project selector. It seems to remain selected upon re-open of the Workspace.

What is the plugin looking for to know if a project is an Ionic project? The `****-app` and `****-marketing-website` are both PHP projects so they shouldn't be considered an Ionic project.

![ionic-vscode-plugin-projects](https://user-images.githubusercontent.com/5725966/208704143-aa4c7f49-22c2-41df-9ef9-6ba73b1f4d95.png)

**Comment by piotr-cz** [comment]
@dtarnawsky Yes, I'm using v1.17.0 for sure.
I can prepare minimal reproducible example but cannot say when :/

@wsamoht How did you open Ionic plugin Project selector?
I can just see actions related to first folder of opened workspace

**Comment by wsamoht** [comment]
> How did you open Ionic plugin Project selector?

@piotr-cz I just clicked on the Ionic plugin icon in the left bar and it was collapsed at the very bottom of the plugin panel.

**Comment by dtarnawsky** [comment]
@wsamoht : The extension will inspect all folders mentioned in the workspace json file and any that have a package.json will show up as projects. Basic functionality like script running and package updates will be displayed and if there is a `ionic.config.json `or `capacitor.config.json` file then additional features from Capacitor will appear.

@piotr-cz: There isn't anything special you need to do in VS Code other than open your workspace file and then click the Ionic extension: the project list should appear in the bottom left. It's always possible there could be a bug in the extension based on your project which is why I would need a sample to reproduce the issue. You can also toggle the developer tools to see if there are any exceptions there which may provide something helpful.

**Comment by piotr-cz** [comment]
Project selector doesn't show, and there are no errors in Developer Tools console.
By the way I'm using [scoped package](https://docs.npmjs.com/cli/v9/using-npm/scope) name.

Below is a screenshot for how the panel looks like when ionic folder is first in workspace list.

![image](https://user-images.githubusercontent.com/612953/208754556-5a150ec5-703f-48b6-987f-d96150886dc1.png)
