### ISSUE TITLE
bug: VSCode Extension - Keybindings Removed

### ISSUE THREAD

**Issue by TelegramUsername** [ionic-team/vscode-extension#72]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Current Behavior

When I use the Keybinding <kbd>Ctrl + R</kbd>, The keybinding is getting prevented by Ionic Extention

### Expected Behavior

When keybinding <kbd>Ctrl + R</kbd> got triggered, VSCode is supposed to show Recent Projects Opened.

### Steps to Reproduce

* Install `ionic.ionic`
* Use keybinding <kbd>Ctrl + R</kbd>
* Nothing will happen
* Uninstall `ionic.ionic`
* Use keybinding <kbd>Ctrl + R</kbd>
* You will see it triggered a VSCode keybinding

### Ionic Info

* Ionic Extension ID: `ionic.ionic`
* Ionic Extension Version: `v1.13.0`

**Comment by liamdebeasi** [comment]
Hey there,

This repo tracker is for bugs in the Ionic Framework codebase. Ionic VSCode Extension issues should be filed here: https://github.com/ionic-team/vscode-extension/issues. I will move this to the appropriate repo.

**Comment by dtarnawsky** [comment]
Hi @TelegramUsername ,

To open up the list of keyboard shortcuts on Windows, go to File > Preferences > Keyboard Shortcuts. On macOS, go to Code > Preferences > Keyboard Shortcuts.

You should be able to find the run command from the Ionic Extension:
![keyboard-shortcuts](https://user-images.githubusercontent.com/84595830/204349949-cc685044-fdd9-4210-9729-941e8e64db9b.png)

Here you change the key binding or remove it if you prefer to use Cmd+R for recent project.
