### ISSUE TITLE
Override run port 8100

### ISSUE THREAD

**Issue by staff0rd** [ionic-team/vscode-extension#73]
When running an app the extension configures 8100 as the port and passes this to `ionic:serve` and sets it in a capacitor.config.json` created at runtime.

How can I configure the extension to use a different port?

**Comment by dtarnawsky** [comment]
Hi @staff0rd,

This will be configured in the next release (1.16.1) by going to `Settings` -> `Advanced`.

**Comment by dtarnawsky** [comment]
Hi @staff0rd,

This feature has been added to the 1.17.0 release by going to `Settings` -> `Advanced`.

**Comment by staff0rd** [comment]
Thanks @dtarnawsky for the quick response & implementation.
