### ISSUE TITLE
Run in iOS getting devices not getting device list

### ISSUE THREAD

**Issue by Joepus** [ionic-team/vscode-extension#75]
After updating to latest Xcode,installing/updating Xcode command line tools and updating all ionic and capacitor CLI's to latest (as of today), the extension is not able to get devices and switches to xcode instead of live reload version within extension.

**Comment by dtarnawsky** [comment]
I assume you mean XCode 14.2. Can you do me a favor and restart your mac and verify if the problem still exists? I'll also update to latest XCode and see if there is a problem there.

**Comment by Joepus** [comment]
Hey thanks for responding! Unfortunately rebooting after installing all did not help. When starting the iOS run as normal via the extension it did return a selection drop-down but it showed "Line 20:1", "line 3:1" etc instead of the device names as usually.

**Comment by dtarnawsky** [comment]
Hi Joepus, 

I've updated to the latest XCode 14.2 and the device list is working as expected (in fact it seems to have fixed a problem with launching the simulator that I saw in 14.1). 

So I'll need some additional information to be able to help you out. Could you screenshot the error you see in the drop down? Also click `Help` -> `Toggle Developer Tools` and see if there are any exceptions/errors in the console log.

**Comment by Joepus** [comment]
Hi dtarnawsky, 
Ok so here is what I learned so far; 
It happens both when choosing Run>Android and Run>iOS. 
At the bottom info bar it indicated a "Getting devices" indicator, then it opens xcode or android studio. Previously it opened just the simulator of choice in live reload as you know. 
I have rebooted several times, removed/reinstalled the extension, removed/reinstalled vscode (with reboots in between each step). 
Tried an exact clone of the project on another system and that still worked as expected. 
I am working on an M1 Max Mac Studio on Ventura 13.0.1. 
The developer console of vscode indicates a "ERR Connection got disposed" for Github co-pilot extension upon startup of vscode. 

![Screenshot 2022-12-15 at 10 10 50](https://user-images.githubusercontent.com/10919765/207819261-2557ecff-8be1-4045-9d34-3ebecac56893.png)
![Screenshot 2022-12-15 at 09 55 30](https://user-images.githubusercontent.com/10919765/207819271-6b23d198-5d7a-4550-b616-d7dfca95181b.png)
![Screenshot 2022-12-15 at 09 55 11](https://user-images.githubusercontent.com/10919765/207819277-3ed78860-acd2-4063-90ac-6350733c0fb6.png)

**Comment by dtarnawsky** [comment]
Hi @Joepus ,

I've released 1.16.0 of the extension and it should log some additional diagnostics to the console when it receives the list of devices. When you are able can you make sure your VS Code updates to 1.16.0 of the extension and then see what is reported in the console (Help -> Toggle Developer Tools).

**Comment by Joepus** [comment]
Really appreciate that dtarnawsky!
![Screenshot 2022-12-15 at 23 15 45](https://user-images.githubusercontent.com/10919765/207979951-e31b0de4-9d56-4fd7-ac20-e4d68c35881f.png)
It actually brought back the list of devices, however, it still opens xcode (in case of ios) instead of just the simulator. It also gathered the list for android devices but also there it opens up android studio and not the simulator. 
Let me know if you want me to check something in particular.

**Comment by dtarnawsky** [comment]
Ok, with the latest 1.16.0 it will prefer the Capacitor CLI over the Ionic CLI for running commands. This tends to suggest that maybe your Ionic CLI is a little dated. I would install latest version in your project.

It sounds like it is now building correctly and is having a problem running. The tool that does this job is `native-run`. Check your version by running `native-run --version` at the command line - it should be `1.7.1`. If it isn't (or you just want to try for good measure) run `npm install native-run -g` to install the tool.

**Comment by Joepus** [comment]
Thanks for your efforts and support. My ionic cli was (although globally at 6.20.4) locally in the project at version 5.4.16 now updated to 6.20.5 and I just tested it in a fresh ionic project and it works again. native-run --version was not available at first, now at 1.7.1 and using the latest version of the extension (1.16.0). In case you wish to test anything further please let me know. 
In addition: choosing run>ios or run>android in the extension now results in running the app directly in simulator with live reload again as expected.

**Comment by dtarnawsky** [comment]
Thanks for the update @Joepus , sounds like updating Ionic CLI and native-run resolved your problem. 

The extension will use the local Ionic CLI (and as of 1.16.0 will prefer to use the Capacitor CLI if available) and it seems like there is a minimum that is needed for all functionality to work. I'll see if I can have the extension detect a low version of the Ionic CLI or missing native-run and warn you - that may help other users running into the same problem.
