### ISSUE TITLE
Run android ends up serving for web

### ISSUE THREAD

**Issue by wimZ** [ionic-team/vscode-extension#76]
After first installation the Run Android functioned correct and fired up an emulator or installed apk on a connected device. 

Now Run Android asks for a device to be selected and ends up serving for web. 

Reinstalling the extension or restarting system has no effect

I have no idea what caused it or where to start investigating. 

Any help is appreciated.

Extension version: v1.16.0
Ionic output:
> npx ionic cap run android -l --external --no-sync --target=42006c60d81794df
> capacitor.cmd sync android
 √ Copying web assets from dist to android\app\src\main\assets\public in 55.24ms
 √ Creating capacitor.config.json in android\app\src\main\assets in 3.79ms
 √ copy android in 97.81ms
 √ Updating Android plugins in 3.39ms
 [info] Found 4 Capacitor plugins for android:
        @capacitor-community/sqlite@4.5.0
        @capacitor/camera@4.1.4
        @capacitor/splash-screen@4.1.2
        capacitor-document-scanner@1.0.1
 √ update android in 138.59ms
 [info] Sync finished in 0.244s
> npm.cmd run ionic:serve -- --host=0.0.0.0 --port=8100
[npm] > testapp@1.0.0 ionic:serve
[npm] > npm run start --host=0.0.0.0 --port=8100
[npm] > testapp@1.0.0 start
[npm] > vite
[npm] 
[npm]   vite v2.9.15 dev server running at:
[npm] 
[npm]   > Local: http://localhost:3000/
[npm]   > Network: use `--host` to expose
[npm]   ready in 1071ms.
[INFO] Waiting for connectivity with npm...

**Comment by dtarnawsky** [comment]
Can you try a couple of things:

1. Turn off live reload and see if it runs on Android
2. Let me know the version of ionic CLI and capacitor CLI you are using. Be sure to update to the latest CLI versions if they are a little old

**Comment by wimZ** [comment]
capacitor/cli : 4.6.1
ionic/cli: 6.20.5

live reload 'on' causes this to happen. the problem goes with the setting. 

However for web, live reload is convenient. (bug?)

Thanks for the advice

**Comment by dtarnawsky** [comment]
If you click the output window you should see what the extension is running. The latest version (v1.19.0) should be calling `--live-reload` rather than `-l` as arguments. The latest version of the Ionic CLI (6.20.6) should fix a problem related to multi projects which may fix your issue.

Can you try out the latest version of the ionic/cli and see if this problem is resolved?

**Comment by wimZ** [comment]
With live-reload off, debug --> web reloads live and run android works, so for me the issue is no longer relevant, but of course willing to assist.

with 1.19.0 live-reload on gives the following:

[Ionic] Pixel 6 API 33 (emulator) Android 13...
> npx ionic cap run android --target=Pixel_6_API_33  --livereload --external
> capacitor.cmd sync android
 √ Copying web assets from dist to android\app\src\main\assets\public in 29.20ms
 √ Creating capacitor.config.json in android\app\src\main\assets in 1.17ms
 √ copy android in 46.72ms
 √ Updating Android plugins in 2.76ms
 [info] Found 5 Capacitor plugins for android:
        @capacitor-community/http@1.4.1
        @capacitor-community/sqlite@4.6.0
        @capacitor/camera@4.1.4
        @capacitor/splash-screen@4.1.2
        capacitor-document-scanner@1.0.1
 √ update android in 161.45ms
 [info] Sync finished in 0.211s
> npm.cmd run ionic:serve -- --host=0.0.0.0 --port=8100
[npm] > truckmateii_cap@1.0.0 ionic:serve
[npm] > npm run start --host=0.0.0.0 --port=8100
[npm] > truckmateii_cap@1.0.0 start
[npm] > vite
[npm] 
[npm]   vite v2.9.15 dev server running at:
[npm] 
[npm]   > Local: http://localhost:3000/
[npm]   > Network: use `--host` to expose
[npm]   ready in 511ms.
[INFO] Waiting for connectivity with npm...
[INFO] Waiting for connectivity with npm...
[INFO] Waiting for connectivity with npm...
[Ionic] Stopped "Android"
[Ionic] node c:\Users\wimz\.vscode-insiders\extensions\ionic.ionic-1.19.0\node_modules\@ionic\cli\bin\ionic cap run android --target=Pixel_6_API_33  --livereload --external Cancelled
[Ionic] Android Completed.
