### ISSUE TITLE
Project not running

### ISSUE THREAD

**Issue by rgilsimoes** [ionic-team/vscode-extension#77]
Ionic:

   Ionic CLI                     : 6.20.6 (C:\Users\ricar\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.8.1
   @angular-devkit/build-angular : 0.1101.4
   @angular-devkit/schematics    : 12.2.7
   @angular/cli                  : 11.2.14
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 4.0.1
   @capacitor/android : 4.0.1
   @capacitor/core    : 4.0.1
   @capacitor/ios     : 4.0.1

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.1

System:

   Android SDK Tools : 26.1.1 (C:\Users\ricar\AppData\Local\Android\Sdk)
   NodeJS            : v14.16.1 (C:\Program Files\nodejs\node.exe)
   npm               : 6.14.12
   OS                : Windows 10
![image](https://user-images.githubusercontent.com/20357414/209665103-d68e2535-d7ce-45d1-90cc-a290a2246e9c.png)

**Comment by dtarnawsky** [comment]
I would give your machine a restart. This would not have anything to do with the extension. If it's repeatable then I would look towards anti-virus and see if its busy scanning your project folder - look at setting up a rule to exclude your project files. The package chokidar is used for file watching by Angulars CLI.

**Comment by rgilsimoes** [comment]
This was probably something temporary due to Angular updates.
