### ISSUE TITLE
Doesn't detect ionic app in mono repo that is two subfolder deep 

### ISSUE THREAD

**Issue by jakkie** [ionic-team/vscode-extension#78]
My ionic app for example is located in my mono repo /app/ionic_web_app/. The extension only detects the ionic app if it is one subfolder deep in the root for example /app. Could support also be added if you have multiple ionic apps in mono repo. Can support be added to search all ionic apps in /app folder for example?

**Comment by dtarnawsky** [comment]
Hi @jakkie ,

It's a good idea to use a mono repo technology for a mono repo. A nest of subfolders is just a hard drive :)

In all seriousness, you can use one of the following:
- [VS Code Workspaces](https://code.visualstudio.com/docs/editor/workspaces#_multiroot-workspaces)
- [Yarn Workspaces](https://classic.yarnpkg.com/lang/en/docs/workspaces/)
- [NPM Workspaces](https://docs.npmjs.com/cli/v7/using-npm/workspaces)
- [PNPM Workspaces](https://pnpm.io/pnpm-workspace_yaml)
- [NX](https://nx.dev/)

I would recommend VS Code Workspaces as it is a quick way to specify what folders are applicable for VS Code development with the additional features around mono repo development of shared package/library management.
