### ISSUE TITLE
1.21.0 - React when run on web - Opens two web views and debug menu. Both web AND a debug view runs. 

### ISSUE THREAD

**Issue by JALabba** [ionic-team/vscode-extension#79]
1.21.0
* Fix for React and Vue projects to open browser when run on web

---
Using chrome as browser. ionic CLI 4.6.1. Repeatable with a bare react project created with the ionic extension.

Current  behavior:  
The extension has two options for checking a site. "run > web" and "debug >web". If you click on "run> web", then the web server is opened in chrome, but the extension also functions as if you clicked "debug" at the same time. if you only click "debug" then the debug view opens normally. 

Expected behavior: 
No debug view opened when clicking the "run > web" command.

**Comment by dtarnawsky** [comment]
Thanks for the bug report @JALabba, this bug should be fixed in 1.21.1 which was just released.
