### ISSUE TITLE
Properties disappeared

### ISSUE THREAD

**Issue by zelnia** [ionic-team/vscode-extension#81]
After some updates, the Configuration->Properties section appear empty.  Otherwise everything works fine but i can't change build number and version number from the extension. 
I'm doing something wrong? Tnx.

**Comment by damiant** [comment]
Hi Zelnia,

Do you have a project you can share?

A zipped copy of your ios and android folders should be enough. The extension reads and writes to the Xcode project and android manifest and related files and there must be something unique about yours.

**Comment by zelnia** [comment]
AndroidManifest.xml in android>app>src>main ?

**Comment by zelnia** [comment]
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">

    <application android:allowBackup="true" android:icon="@mipmap/ic_launcher" android:label="@string/app_name" android:roundIcon="@mipmap/ic_launcher_round" android:supportsRtl="true" android:theme="@style/AppTheme">

        <activity android:exported="true" android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode" android:name="com.xxx.yyyyy.MainActivity" android:label="@string/title_activity_main" android:theme="@style/AppTheme.NoActionBarLaunch" android:launchMode="singleTask">

            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>

        </activity>

        <provider android:name="androidx.core.content.FileProvider" android:authorities="${applicationId}.fileprovider" android:exported="false" android:grantUriPermissions="true">
            <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/file_paths"/>
        </provider>
    </application>

    

    <uses-permission android:name="android.permission.INTERNET"/>
</manifest>

**Comment by dtarnawsky** [comment]
Hi @zelnia,

There isn't any issues with your `androidmanifest.xml` file. Would it be possible to share your source? You can send a link to it to damian at ionic dot com.

**Comment by dtarnawsky** [comment]
Closing as I do not believe there is an issue here.

**Comment by zelnia** [comment]
The problem is still there. But i can set android version from android studio so its not very important. Tnx for help.

**Comment by dtarnawsky** [comment]
Ok @zelnia, if you can share a zip of your project that would help - you can remove the JS source and just leave the project structure and that can help to reproduce the problem. Just email the zip (or a link to it) to damian at ionic dot io.
