### ISSUE TITLE
Debug for Web launches an encoded url

### ISSUE THREAD

**Issue by wimZ** [ionic-team/vscode-extension#83]
When I debug -> web, the extension tries to start the following URL:
[Ionic] Launching [36mhttp://localhost:[1m3000[22m/[39m
[npm]   > Local: http://localhost:3000/

resulting in a browser about:blank

Reinstalled the extension, @capacitor/cli 

extension version v1.21.5

**Comment by dtarnawsky** [comment]
Thanks for the bug report @wimZ,

I would guess you are using a framework that uses Vite perhaps?

In any case, I found a scenario where the URL mentioned in logs is colored, and the extension needed to strip out the color characters in order to access the URL. This has been fixed in version 1.21.6 which is now released. Please give it a try and let me know if it fixes the issue.

**Comment by wimZ** [comment]
Thans for your update.

Just tested with v 1.21.6 and indeed it is fixed.

Thanks !!!

Van: Damian Tarnawsky ***@***.***>
Verzonden: maandag 23 januari 2023 15:27
Aan: ionic-team/vscode-extension ***@***.***>
CC: wimZ ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [ionic-team/vscode-extension] Debug for Web launches an encoded url (Issue #83)


Thanks for the bug report @wimZ<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FwimZ&data=05%7C01%7C%7Cdec0ea9dd0ac48ed9ff008dafd4de954%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638100808318763136%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=6ugwLfpuU9Xz4jtIOBJLILogfr1qs2TGq2CBsThwl0g%3D&reserved=0>,

I would guess you are using a framework that uses Vite perhaps?

In any case, I found a scenario where the URL mentioned in logs is colored, and the extension needed to strip out the color characters in order to access the URL. This has been fixed in version 1.21.6 which is now released. Please give it a try and let me know if it fixes the issue.

-
