### ISSUE TITLE
Console does not correctly detect NX workspaces

### ISSUE THREAD

**Issue by Swanzor** [ionic-team/vscode-extension#84]
Hi I am using an NX workspace that has various applications and some of those apps are Capacitor projects with their own `capacitor.config.ts` files and Android/iOS folders. (see image below for top level project folder structure)

![image](https://user-images.githubusercontent.com/61963904/214009712-dad26165-27b6-4f28-ab1b-fee7a41b949c.png)

Below is an image of the folder structure of one of the Capacitor apps

![image](https://user-images.githubusercontent.com/61963904/214010314-cad1a5e5-9eb0-4f6c-8829-856eb432f00b.png)

When I switch to the Ionic console it loads and then shows a basic console that does not  show any of the application or "NX PROJECTS" panel, as was demonstrated in the video.

![image](https://user-images.githubusercontent.com/61963904/214011007-a680bf80-859f-42a4-bf97-a41e90724010.png)

I have no idea how to get it working as the docs have no section that states otherwise

**Comment by dtarnawsky** [comment]
Hi @Swanzor, 

You should only need to open the root folder (the one that contains `nx.json`) for the Ionic extension to know what to do with your NX mono repo (and for the "NX Projects" to appear). Can you try that?
