### ISSUE TITLE
.nvmrc support

### ISSUE THREAD

**Issue by francescodoffizi** [ionic-team/vscode-extension#88]
It would be useful to set up or allow the extension to capture nvmrc parameter in the project folder to force the use specific Node version.

Trying some VSCode plugins is useless.

**Comment by dtarnawsky** [comment]
Thanks for the suggestion @francescodoffizi ,

Are you thinking of having the extension run `nvm use 16` for example to use node 16 and then all subsequent commands would be using that version?

**Comment by ltfschoen** [comment]
well if have a project and you created a .nvmrc file and added the contents "v19.6.0" to it, then all you need to do to install that version of Node.js via NVM is to follow the steps to install NVM and then run `nvm use` and it automatically installs whatever version you specified in that file.

**Comment by francescodoffizi** [comment]
If I create an Ionic project (or better I've got an old one), that needs a specific version I put the .nvmrc file in the project root but Ionic shortcuts in VSCode (build, run and debug) ignores the .nvmrc.
Nvmrc Is read in the VSCode internal terminal cause of bashrc/zshrc (on Mac) helper scripts.

The expected behaviour is that even launching debug or running via Ionic extensions, nvmrc is elaborated.

Now the only solution is to set the nvm default before VSCode launch, making nvmrc useless.

**Comment by dtarnawsky** [comment]
Hi @ltfschoen and @francescodoffizi ,

Version 1.24.0 has just been released and it has support for `.nvmrc`!

If your project has a `.nvmrc` file at its base folder then it will call `nvm use` before running node commands.
