### ISSUE TITLE
Run on device does not install app and run (iOS)

### ISSUE THREAD

**Issue by ghost** [ionic-team/vscode-extension#89]
When I select the Capacitor / Run On Device option for iOS everything looks good in the output console and it ends with the message " App deployed to device!" but the app does not open and is in fact not installed.

If I then jump over to the command line and run:

ionic capacitor run ios --no-sync --target XXX

it installs ok. So its only from the VS Studio that it is not working.

**Comment by dtarnawsky** [comment]
Hi @richardkshergold,

I was able to reproduce this on iOS for real devices in both the extension and using Capacitor CLI. It is intermittent however but I should be able to discuss it with the Capacitor team to see why it might happen with real devices.

**Comment by ghost** [comment]
Thanks - actually it's not working for me using the CLI or the extension right now

**Comment by dtarnawsky** [comment]
Hey @richardkshergold, I've tracked this down to Node 18. If you switch to Node 16 it will work. A [PR](https://github.com/ionic-team/native-run/pull/275) on a dependency called `native-run` is outstanding and once that is merged and released then the problem should disappear by reinstalling node_modules.

**Comment by richardshergold** [comment]
Thank you!

**Comment by dtarnawsky** [comment]
Hi @richardshergold,

The issue related to native-run has been fixed and released in 1.7.2. To update your project all you should need to do is:
`npm update`

The Capacitor CLI will use the latest version of native-run and it should run the app.
