### ISSUE TITLE
Persistent error related to NODE_TLS_REJECT_UNAUTHORIZED on console

### ISSUE THREAD

**Issue by rgilsimoes** [ionic-team/vscode-extension#96]
I'm getting this error on the console:

[error] (node:7100) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)

Ionic VS Code extension v1.29.1
Version: 1.76.1 (user setup)
Commit: 5e805b79fcb6ba4c2d23712967df89a089da575b
Date: 2023-03-08T16:32:00.131Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

Global npm packages:
@angular/cli        15.0.4
@capacitor/cli       4.6.1
@ionic/cli          6.20.6
cordova             11.0.0

**Comment by dtarnawsky** [comment]
You have the environment variable NODE_TLS_REJECT_UNAUTHORIZED set to 0 in your shell. You'll need to find that and remove it. This has to do with your node setup on your computer and is unrelated to the extension.

**Comment by rgilsimoes** [comment]
I found it to be set by MySQL extension:

![image](https://user-images.githubusercontent.com/20357414/224505851-560f6fe1-4143-4199-a1b8-395466637607.png)

Disabling it removes the error.
