### ISSUE TITLE
NX Monorepo support is broken with NX 15

### ISSUE THREAD

**Issue by distante** [ionic-team/vscode-extension#97]
After updating an NX monorepo to version 15, the extension does not find the correct app where Ionic is implemented.

It even does not recognize all the projects that exist on the monorepo as before.

Previously it worked as expected.

**Comment by damiant** [comment]
Can you provide a code repo that has the problem? Or the nx.json and workspace.json files.

We recently added support for later NX versions and that may have affected yours.

**Comment by distante** [comment]
`workspace.json` is removed now (well deprecated but after update it is not there anymore) https://nx.dev/deprecated/workspace-json

nx.json
```
{
  "affected": {
    "defaultBase": "dev"
  },
  "npmScope": "my-company",
  "tasksRunnerOptions": {
    "default": {
      "runner": "@nrwl/nx-cloud",
      "options": {
        "cacheableOperations": [
          "build",
          "lint",
          "test",
          "e2e",
          "integration",
          "test-integration",
          "build-storybook",
          "component-test",
          "generate-api-client",
          "generate-swagger-wait-for-generation-step",
          "generate-swagger"
        ],
        "parallel": 1,
        "accessToken": "my-access-tocken"
      }
    }
  },
  "defaultProject": "my-project-backend-ui",
  "generators": {
    "@nrwl/angular": {
      "application": {
        "linter": "eslint"
      },
      "library": {
        "linter": "eslint"
      },
      "storybook-configuration": {
        "linter": "eslint"
      }
    },
    "@nrwl/angular:application": {
      "style": "css",
      "linter": "eslint",
      "unitTestRunner": "jest",
      "e2eTestRunner": "cypress"
    },
    "@nrwl/angular:library": {
      "linter": "eslint",
      "unitTestRunner": "jest",
      "prefix": "my",
      "setParserOptionsProject": true,
      "standaloneConfig": true,
      "strict": true
    },
    "@nrwl/nest:library": {
      "linter": "eslint",
      "unitTestRunner": "jest",
      "prefix": "my",
      "setParserOptionsProject": true,
      "standaloneConfig": true,
      "strict": true
    },
    "@nrwl/node:library": {
      "linter": "eslint",
      "unitTestRunner": "jest",
      "prefix": "my",
      "setParserOptionsProject": true,
      "standaloneConfig": true,
      "strict": true
    },
    "@nrwl/angular:component": {
      "style": "css",
      "changeDetection": "OnPush"
    },
    "@schematics/angular:component": {
      "style": "css",
      "changeDetection": "OnPush"
    },
    "@nrwl/angular:scam": {
      "flat": false,
      "inlineScam": false
    },
    "@nrwl/angular:scam-directive": {
      "flat": false,
      "inlineScam": false
    },
    "@nrwl/angular:scam-pipe": {
      "flat": false,
      "inlineScam": false
    }
  },
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  "targetDefaults": {
    "build": {
      "dependsOn": ["^build"],
      "inputs": ["production", "^production"]
    },
    "integration": {
      "inputs": ["default", "^production"]
    },
    "e2e": {
      "inputs": ["default", "^production"]
    },
    "test": {
      "inputs": ["default", "^production", "{workspaceRoot}/jest.preset.js"]
    },
    "test-integration": {
      "inputs": ["default", "^production", "{workspaceRoot}/jest.preset.js"]
    },
    "lint": {
      "inputs": [
        "default",
        "{workspaceRoot}/.eslintrc.json",
        "{workspaceRoot}/tools/eslint-rules/**/*"
      ]
    },
    "build-storybook": {
      "inputs": ["default", "^production", "{workspaceRoot}/.storybook/**/*"]
    },
    "component-test": {
      "inputs": ["default", "^production"]
    },
    "generate-swagger-wait-for-generation-step": {
      "inputs": ["default", "^production"]
    },
    "generate-swagger": {
      "inputs": ["default", "^production"]
    }
  },
  "namedInputs": {
    "default": ["{projectRoot}/**/*", "sharedGlobals"],
    "sharedGlobals": [],
    "production": [
      "default",
      "!{projectRoot}/**/?(*.)+(integration-spec|spec|test|stub).[jt]s?(x)?(.snap)",
      "!{projectRoot}/tsconfig.(spec|integration-spec).json",
      "!{projectRoot}/jest.config.[jt]s",
      "!{projectRoot}/jest.config.integration.[jt]s",
      "!{projectRoot}/.eslintrc.json",
      "!{projectRoot}/.storybook/**/*",
      "!{projectRoot}/**/*.stories.@(js|jsx|ts|tsx|mdx)",
      "!{projectRoot}/cypress/**/*",
      "!{projectRoot}/**/*.cy.[jt]s?(x)",
      "!{projectRoot}/cypress.config.[jt]s",
      "!{projectRoot}/cypress.integration.config.[jt]s"
    ]
  }
}


```

**Comment by dtarnawsky** [comment]
Hey @distante,

Can you try version 1.30 of the extension that was just released?

It includes some NX fixes and was tested with a newer NX repository. It is still possible you'll have an issue with NX support as it's quite unique how it has changed with NX 15. I may still need a sample project that reproduces the problem you are seeing. Is it that you cannot see every single library in the NX repo? The extension will only list projects that look like they are related to Ionic, Web, or Capacitor so perhaps it is just filtering out some projects?

**Comment by distante** [comment]
Sadly, it still does not work.

I will see if I can put together something, sadly I can not share the repo where I see it because it does not belong to me.

> Is it that you cannot see every single library in the NX repo? 

I see two NX Projects, one is an app that does not have anything to do with Ionic, and the other one is not really a project but a folder name inside the `apps` folder and the `libraries` folder.

A way to point the extension to the Ionic/capacitor application would be a quick fix I think.

**Comment by distante** [comment]
As tip, something that I learned just now, you can get the name of the apps with
```
npx nx print-affected  --type=app --all
```

or you can write it to a `json` file
```
npx nx print-affected  --type=app --all > print-affected.json
```

https://nx.dev/packages/nx/documents/print-affected

**Comment by dtarnawsky** [comment]
Hey @distante ,

Thanks for the update on this. v1.30.1 has been released and the extension now uses `nx print-affected` for its project list, if that returns no projects then it will iterate through the apps folder looking for folders. It will also use `workspace.json` if you have an older project.

This also means that you only get apps listed as projects and not libs. Hopefully that is what you are after.

**Comment by distante** [comment]
Hi @dtarnawsky, no, no luck, I see in the output that the names are found but the correct path is not resolved.

```
[error] The NX project "client-ionic-app-ui" does not exist at /Users/saninn/dev/work/apps/client-ionic-app-ui
```

and that happens, because the real path is:
```
/Users/saninn/dev/work/apps/client/client-ionic-app-ui
```

I wanted to create a pull request or something but I realized the extension code is not open source.

What I do to trigger some things locally is create a map of the apps and paths from their `project.json` file, for that, I do this (on mac)

```
find ./apps ./libs -name 'project.json'
```
then I parse the `name` property and remove the `project.json` part of the path and now I have both the library name and the path.

You can also check which projects are apps checking for `"projectType": "application"`

:)

**Comment by dtarnawsky** [comment]
Thanks for the helpful info @distante,

In 1.31.0 the extension navigates subfolders looking for project.json. Hopefully this should work for your project.

**Comment by distante** [comment]
Hi thanks, now I see all the projects there.
