### ISSUE TITLE
Run Android command ends with error: unknown option '--target=4200601ae4d994ff'

### ISSUE THREAD

**Issue by wimZ** [ionic-team/vscode-extension#98]
vscode extension 136,041
cap 4.7.0

Run Android issues different command sets depending on the state of the project. 

When run is started after a project change this commandline is created.  I looks like ' && ' is missing between 'npx cap copy' and 'npx cap run'.  A such modified line in terminal runs OK.

Commandline:

[Ionic] samsung SM-J330FN Android 9...
> npx ionic build && npx cap copynpx cap run android --target=4200601ae4d994ff  --external --no-build --no-sync

Result

error: unknown option '--target=4200601ae4d994ff'
[error] node "c:\Users\wimz\.vscode-insiders\extensions\ionic.ionic-1.30.0\node_modules\@ionic\cli\bin\ionic" build && npx cap copynpx cap run android --target=4200601ae4d994ff  --external --no-build --no-sync Failed
[error] Android Failed.

**Comment by dtarnawsky** [comment]
Thanks for the bug report @wimZ,

This was a problem with the v1.30 release, so we've fixed and released v1.30.1 to fix the problem (which VS Code should have updated to for you). Sorry for the inconvenience.
